### ISSUE TITLE
No events received when using `mysql-binlog-connector-java` with scala

### ISSUE THREAD

**Issue by simao** [shyiko/mysql-binlog-connector-java#10]
Hello,

I am trying to use this package with scala and I am running into some problems.

Reading from a local binlog file works.

I am using the following code to read from a remote server:

``` scala
val client = new BinaryLogClient("127.0.0.1", 9797, "user", "pass")

client.registerEventListener(new EventListener() {
  def onEvent(event: Event) {
    println("New event")
  }
})

client.connect
```

But nothing happens when I run this code.

I have a ssh tunnel on port 9797 forwarding to mysql server. Connecting with the `mysqlbinlog` command on that server works.

Any idea on how to debug this? Probably not even a problem of `mysql-binlog-connector-java` but I am not sure how to debug.

Thanks.

**Comment by hoffin688** [comment]
Hello,

date format not converting to elasticsearch date format, getting exception java.util.date cannot cast to string, unsafe domain object conversion.
