### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by reiz** [shyiko/mysql-binlog-connector-java#101]
Why not publishing this project on [Maven Central](http://search.maven.org/)? Here is the guide how to do it: https://maven.apache.org/guides/mini/guide-central-repository-upload.html. The initial setup is a bit shitty, but after that every deployment is a single command ;-) 

By the way, I'm the guy behind VersionEye and this project was submitted to VersionEye. Obviously somebody wants to get notified as soon a new version of this library comes out. If the project is on Maven Central it is tracked automatically by VersionEye ;-)

**Comment by shyiko** [comment]
Hi. Not sure what you mean. mysql-binlog-connector-java has been in Maven Central for a long time now (since 2014) (https://www.versioneye.com/java/com.github.shyiko:mysql-binlog-connector-java/0.3.1). Am I missing something?

**Comment by reiz** [comment]
Ah, OK. In that case sorry. Somehow I missed it :-)

**Comment by shyiko** [comment]
@reiz no worries. :beers:
