### ISSUE TITLE
Deserialization of V2 timestamp might be incorrect

### ISSUE THREAD

**Issue by rhauch** [shyiko/mysql-binlog-connector-java#106]
_Applies to 0.3.1, but not to `master` branch which has changed the semantics of the temporal value deserialization logic._

MySQL's representation of `TIMESTAMP` values is [documented here](http://dev.mysql.com/doc/internals/en/date-and-time-data-type-representation.html), and changed in MySQL 5.6.4. However, the documentation also states that semantics are not changed:

> As of MySQL 5.6.4 the TIME, TIMESTAMP, and DATETIME types can have a fractional seconds part. Storage for these types is big endian (for memcmp() compatibility purposes), with the nonfractional part followed by the fractional part. ...
> TIMESTAMP encoding for nonfractional part: Same as before 5.6.4, except big endian rather than little endian

However, in 0.3.1's `AbstractRowsEventDataDeserializer.java` the `deserializeTimestamp` method is [this](https://github.com/shyiko/mysql-binlog-connector-java/blob/0.3.1/src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/AbstractRowsEventDataDeserializer.java#L217):

    private java.sql.Timestamp deserializeTimestamp(ByteArrayInputStream inputStream) throws IOException {
        long value = inputStream.readLong(4);
        return new java.sql.Timestamp(value * 1000L);
    }

while the `deserializeTimestampV2` is [this](https://github.com/shyiko/mysql-binlog-connector-java/blob/0.3.1/src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/AbstractRowsEventDataDeserializer.java#L222):

    private java.sql.Timestamp deserializeTimestampV2(int meta, ByteArrayInputStream inputStream) throws IOException {
        // big endian
        long timestamp = bigEndianLong(inputStream.read(4), 0, 4);
        Calendar c = Calendar.getInstance();
        c.setTimeInMillis(timestamp * 1000);
        c.set(Calendar.MILLISECOND, getFractionalSeconds(meta, inputStream));
        return new java.sql.Timestamp(c.getTimeInMillis());
    }

The `deserializeTimestamp` method is simply reading the seconds past epoch directly and creating the `java.sql.Timestamp` object, and seems to be correct. However, the `deserializeTimestampV2` method is using a local `Calendar` to obtain the milliseconds past epoch (in UTC), when the MySQL documentation seems to state that, like prior to 5.6.4, the timestamp value still represents the milliseconds past epoch; using a `Calendar` will treat the timestamp as if it were a local timestamp, and will result in a timezone conversion.

**Comment by shyiko** [comment]
0.3.3
