### ISSUE TITLE
Converting Event.toString back to Event

### ISSUE THREAD

**Issue by Dakarun** [shyiko/mysql-binlog-connector-java#109]
Using the binlog connector I have built a data processor which can be used to stream data to various destinations after being processed and mapped. In order to ensure I can recover or reprocess events I am also storing them to text files.

However I'm facing some difficulty mapping the event from a string to the Event class. Using regex I can extract the header and data, but from what I understand the only way I make this work is by storing the serialized object to deserialize later. This is something I would prefer to avoid. Is there any way around this?

Thanks!

**Comment by jolivares** [comment]
Why don't you use the binlog coordinates (file name, position) to keep a record of the last processed event? In case of having to recover from a failure you just need to start reading from the last binlog coordinate.

**Comment by Dakarun** [comment]
I thought about that, and that's my backup plan, but I want to use a messaging system such as Kafka to be able to distribute the unprocessed event if there is a need to scale out.

**Comment by shyiko** [comment]
Event.toString() isn't going to cut it. You gonna need a proper serialization/deserialization mechanism. You could opt for something like jackson or gson to have events stored as JSON objects or something more space-efficient like msgpack/avro/<so many other options>.

**Comment by Dakarun** [comment]
Thanks for the tips, I'll check them out.
