### ISSUE TITLE
how to konw the events for the same operation!

### ISSUE THREAD

**Issue by tonyC2016** [shyiko/mysql-binlog-connector-java#111]
when i use onEvent for EventListener,if i do a update operation ,there are five event as below:
how can i konw the five is for the same one operation ?
Event{header=EventHeaderV4{timestamp=1473453787000, eventType=GTID, serverId=184054, headerLength=19, dataLength=46, nextPosition=757483072, flags=0},
 data=GtidEventData{flags=1, gtid='23b618c4-33f8-11e6-82ae-40167e67e7eb:91855'}}
 
Event{header=EventHeaderV4{timestamp=1473453787000, eventType=QUERY, serverId=184054, headerLength=19, dataLength=55, nextPosition=757483146, flags=8}, 
data=QueryEventData{threadId=35909, executionTime=0, errorCode=0, database='report', sql='BEGIN'}}

Event{header=EventHeaderV4{timestamp=1473453787000, eventType=TABLE_MAP, serverId=184054, headerLength=19, dataLength=39, nextPosition=757483204, flags=0}, 
data=TableMapEventData{tableId=624, database='report', table='student', columnTypes=3, 3, 15, 3, 3, columnMetadata=0, 0, 30, 0, 0, columnNullability={}}}

Event{header=EventHeaderV4{timestamp=1473453787000, eventType=EXT_UPDATE_ROWS, serverId=184054, headerLength=19, dataLength=63, nextPosition=757483286, flags=0},
 data=UpdateRowsEventData{tableId=624, includedColumnsBeforeUpdate={0, 1, 2, 3, 4}, includedColumns={0, 1, 2, 3, 4}, rows=[
    {before=[2, 231, T-BAG, 2, 3], after=[2, 31, T-BAG, 2, 3]}
]}}

Event{header=EventHeaderV4{timestamp=1473453787000, eventType=XID, serverId=184054, headerLength=19, dataLength=12, nextPosition=757483317, flags=0}, data=XidEventData{xid=11901121}}

**Comment by shyiko** [comment]
Hi. 

(from [readme.md](https://github.com/shyiko/mysql-binlog-connector-java#frequently-asked-questions)): 

> Q. How does a typical transaction look like?
A. GTID event (if gtid_mode=ON) -> QUERY event with "BEGIN" as sql -> ... -> XID event | QUERY event with "COMMIT" or "ROLLBACK" as sql.

You might want to take a look at [rook/MySQLReplicationStream](https://github.com/shyiko/rook/blob/master/rook-source-mysql/src/main/java/com/github/shyiko/rook/source/mysql/MySQLReplicationStream.java#L211) (it aggregates multiple events that represent a single transaction).

**Comment by tonyC2016** [comment]
@shyiko ,i konw the order ofevents, i wanna konw if exits that scenes: concurrency transaction ,is there any scenes that two transaction occur at the same time ,and receive the two events at the same time ,and 
upset the order of the events, is it exits?

**Comment by shyiko** [comment]
no, multiple concurrent transactions will not be intertwined when written to the binary log.

**Comment by tonyC2016** [comment]
ok,3q
