### ISSUE TITLE
Binary columns are returned as strings instead of byte arrays

### ISSUE THREAD

**Issue by thesamet** [shyiko/mysql-binlog-connector-java#112]
This seems like a known issue addressed by #56 via 117b92776d74cd6727c373114ce5ddc7b3939a65, then the behavior reverted by commit 02a7f3e6c5f5a4dbf22a1370c5a87be8df7fd663.

**Comment by shyiko** [comment]
Hi Nadav. It wasn't reverted - https://github.com/shyiko/mysql-binlog-connector-java/commit/02a7f3e6c5f5a4dbf22a1370c5a87be8df7fd663#diff-5ff2728d4cbb6c39c4987aea7c7f2e2cR297. This change wasn't incorporated into 0.x due to breaking backward compatibility and is scheduled for 1.0.0 (until then you can [register your own](https://github.com/shyiko/mysql-binlog-connector-java#controlling-event-deserialization) *RowsEventDeserializer (including the one from master)).

**Comment by thesamet** [comment]
Thanks for the quick response. There's something about this workaround that I haven't figured out how to do nicely. All these *RowsEventDeserializers require a `Map<Long, TableMapEventData> tableMapEventByTableId`, however this is a private element of `EventDeserializer`. So I would have to basically swap out all deserializers that need this, and not just the single one I care about...

**Comment by shyiko** [comment]
@thesamet Yeah, right now getting custom *RowsEventDataDeserializer registered is ugly (code provided below). This mess is going to be rectified in 1.0.0 as part of https://github.com/shyiko/mysql-binlog-connector-java/issues/107. Note that until that ticket is resolved you need to provide 3 (Write aka 'insert'|Update|Delete) RowsEventDataDeserializer|s.

```java
final BinaryLogClient client = ...
final Map<Long, TableMapEventData> tableMapEventByTableId = new HashMap<Long, TableMapEventData>();
final Map<EventType, EventDataDeserializer> eventDataDeserializers = new HashMap<EventType, EventDataDeserializer>() {{
    put(EventType.FORMAT_DESCRIPTION, new FormatDescriptionEventDataDeserializer());
    put(EventType.ROTATE, new RotateEventDataDeserializer());
    put(EventType.INTVAR, new IntVarEventDataDeserializer());
    put(EventType.QUERY, new QueryEventDataDeserializer());
    put(EventType.TABLE_MAP, new TableMapEventDataDeserializer());
    put(EventType.XID, new XidEventDataDeserializer());
    put(EventType.WRITE_ROWS,
        new CustomWriteRowsEventDataDeserializer(tableMapEventByTableId));
    put(EventType.UPDATE_ROWS,
        new CustomUpdateRowsEventDataDeserializer(tableMapEventByTableId));
    put(EventType.DELETE_ROWS,
        new CustomDeleteRowsEventDataDeserializer(tableMapEventByTableId));
    put(EventType.EXT_WRITE_ROWS,
        new CustomWriteRowsEventDataDeserializer(tableMapEventByTableId).
            setMayContainExtraInformation(true));
    put(EventType.EXT_UPDATE_ROWS,
        new CustomUpdateRowsEventDataDeserializer(tableMapEventByTableId).
            setMayContainExtraInformation(true));
    put(EventType.EXT_DELETE_ROWS,
        new CustomDeleteRowsEventDataDeserializer(tableMapEventByTableId).
            setMayContainExtraInformation(true));
    put(EventType.ROWS_QUERY, new RowsQueryEventDataDeserializer());
    put(EventType.GTID, new GtidEventDataDeserializer());
}};
client.setEventDeserializer(new EventDeserializer(new EventHeaderV4Deserializer(),
    new NullEventDataDeserializer(), eventDataDeserializers, tableMapEventByTableId));
...
```

**Comment by thesamet** [comment]
For reference, here's what I ended up with. Careful, Scala...

```
class MyExtWriteRowsDeserializer(tableMapEventData: util.Map[java.lang.Long, TableMapEventData])
  extends WriteRowsEventDataDeserializer(tableMapEventData) {

  override def deserializeString(length: Int, inputStream: ByteArrayInputStream): Serializable = {
    val stringLength = if (length < 256) inputStream.readInteger(1) else inputStream.readInteger(2)
    inputStream.read(stringLength)
  }
}

object MyWatcher {
  def main(args: Array[String]): Unit = {
    val client = new BinaryLogClient(...)
    val tableMap = new util.HashMap[java.lang.Long, TableMapEventData]
    val eventMap = new util.HashMap[EventType, EventDataDeserializer[_]]
    eventMap.put(EventType.EXT_WRITE_ROWS, new MyExtWriteRowsDeserializer(tableMap).setMayContainExtraInformation(true))
    eventMap.put(EventType.WRITE_ROWS, new MyExtWriteRowsDeserializer(tableMap))
    eventMap.put(EventType.TABLE_MAP, new TableMapEventDataDeserializer())
    val eventDeserializer = new EventDeserializer(
      new EventHeaderV4Deserializer, new NullEventDataDeserializer, eventMap, tableMap)
    client.setEventDeserializer(eventDeserializer)
```

**Comment by shyiko** [comment]
@thesamet 👍 

P.S. you might want to override WriteRowsEventDataDeserializer::`deserializeVarString` too (unless you don't care about VARBINARY).

**Comment by dingxiaobo** [comment]
`CHAR_AND_BINARY_AS_BYTE_ARRAY` can solve this. by https://github.com/shyiko/mysql-binlog-connector-java/commit/340713d7ab831a9b69a8c11fb6f931c006c332a5

But you need handle `VARCHAR` type by your own after this `CompatibilityMode` set.
