### ISSUE TITLE
String representation in JSON support may be unexpected

### ISSUE THREAD

**Issue by rhauch** [shyiko/mysql-binlog-connector-java#120]
The recent change to support MySQL 5.7's `JSON` type added a utility that can parse the MySQL internal binary format in which such values appear in the binlog, and call the appropriate methods on the supplied `JsonFormatter` class. The `JsonStringFormatter` behaves as one might expect for JSON objects and JSON values, but because MySQL allows storing _scalar values_ in a `JSON` column, the string formatter has to handle these scalar values.

Consider a scalar value that is the integer `123`. In this case, the `JsonStringFormatter` would result in a Java string that contains three characters:

```
123
```

However, consider a scalar value that is the string "123". In this case, the `JsonStringFormatter` would result in a Java string that contains 5 characters:

```
"123"
```

The double quotes are included in the Java string to denote that the value is a string (rather than a numeric or boolean). This same approach is used for all scalar values that are convertible to strings (e.g., DATE, TIME, DATETIME, etc.).

While this might be useful, some clients may actually want to avoid having the double quotes in the Java string output by the formatter. The `JsonStringFormatter` should have an option that controls whether string scalar values are wrapped by double quotes, and the static methods in the `JsonBinary` class should expose this option.

**Comment by rhauch** [comment]
@shyiko, I hope this is clear. I'm not sure which way is better, but I think Debezium would rather the strings did not have the double quotes. However, that means that clients may not be able to distinguish between scalar values that were ints versus strings, so I do think it's useful to keep the current behavior (at least as an option).

Thoughts? I'm working on a PR and should have one available shortly.

**Comment by shyiko** [comment]
@rhauch I think current behavior (strings should wrapped in double quotes) is the only correct one. "123" and 123 are perfectly valid JSON structures (see http://www.json.org/, you can also try any online validator like http://jsonlint.com/).

**Comment by rhauch** [comment]
@shyiko, yeah, you're right. I guess I didn't know that the scalar values are legal on their own. Thanks. I'll close without any changes.

**Comment by shyiko** [comment]
@rhauch No worries 🍻
