### ISSUE TITLE
Blocking Mode Problem

### ISSUE THREAD

**Issue by az3** [shyiko/mysql-binlog-connector-java#121]
Hello,

We are using mysql-binlog-connector-java 0.5.0 but blocking mode does not seem to work for us. Maybe it's because of the server but we couldn't find a way to debug.

The MySQL server we are connecting (v5.7.14) does not have too much traffic (~ 10 inserts per second); thus binlog application can keep up very fast. And when the binlog application reaches end of log, it stops & reconnects (in the keepAlive interval). If we connect to MySQL Server v5.6 blocking mode works as intended. But with MySQL Server v5.7, every 10 seconds the connection drops and reconnects.

Also, in 5.6 Server GTID is not enabled, but 5.7 server has ANONYMOUS_GTID events in binlog files, may be it's related but we found no relation. We also saw this, maybe related: http://bugs.mysql.com/bug.php?id=71178

In the end, the application works fine (10 seconds lag is OK for us) but we want to improve. Is there any way you can propose us for debugging, how can we debug this issue?

Thanks.

Notes: Sorry for the long details, I want to provide as much information as I can.

- Version details are provided below;
```
Server version: 5.7.14-7-log Percona Server (GPL), Release 7, Revision 083e298
mysql/mysql-connector-java version: 5.1.38
com.github.shyiko/mysql-binlog-connector-java version: 0.5.0
```

- Implementation connect details are below;
```
BinaryLogClient client = new BinaryLogClient(host, port, user, pass);
client.setKeepAlive(true); // default true
client.setBlocking(true); // default true
client.setKeepAliveConnectTimeout(10000L); // 10 Seconds
client.setKeepAliveInterval(10000L); // 10 Seconds
// ...
client.connect();
```

- Reconnection log is below;
```
Oct 07, 2016 12:56:42 PM com.github.shyiko.mysql.binlog.BinaryLogClient$3 run
INFO: Trying to restore lost connection to 10.123.123.123:3320
Oct 07, 2016 12:56:42 PM com.github.shyiko.mysql.binlog.BinaryLogClient connect
INFO: Connected to 10.123.123.123:3320 at mysql-bin.000258/1059234495 (sid:65535, cid:240155)

Oct 07, 2016 12:56:52 PM com.github.shyiko.mysql.binlog.BinaryLogClient$3 run
INFO: Trying to restore lost connection to 10.123.123.123:3320
Oct 07, 2016 12:56:53 PM com.github.shyiko.mysql.binlog.BinaryLogClient connect
INFO: Connected to 10.123.123.123:3320 at mysql-bin.000258/1059611004 (sid:65535, cid:240178)

Oct 07, 2016 12:57:03 PM com.github.shyiko.mysql.binlog.BinaryLogClient$3 run
INFO: Trying to restore lost connection to 10.123.123.123:3320
Oct 07, 2016 12:57:03 PM com.github.shyiko.mysql.binlog.BinaryLogClient connect
INFO: Connected to 10.123.123.123:3320 at mysql-bin.000258/1059985158 (sid:65535, cid:240200)

Oct 07, 2016 12:57:13 PM com.github.shyiko.mysql.binlog.BinaryLogClient$3 run
INFO: Trying to restore lost connection to 10.123.123.123:3320
Oct 07, 2016 12:57:13 PM com.github.shyiko.mysql.binlog.BinaryLogClient connect
INFO: Connected to 10.123.123.123:3320 at mysql-bin.000258/1060354060 (sid:65535, cid:240224)
```

**Comment by shyiko** [comment]
Hi @az3. Can you please try setting [client.setServerId(...)](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L238) before connect. Each instance of mysql-binlog-connector-java/BinaryLogClient, mysqlbinlog, MySQL server must have unique server id assigned to them otherwise connections with same server-id will be dropped. If that doesn't work - any chance you could have docker image or vagrant box with your configuration of Percona Server (5.7.14-7)?

**Comment by az3** [comment]
Thanks for feedback; probably "same server id" problem occurs for us, there are 2 binlog connector instances connecting to that server. I need to take a look.

I'll also try building up an image but it may take time. I'll report back my findings.

Cheers.

**Comment by az3** [comment]
Thank you very much Shyiko. Setting a different serverId for each client fixed the problem. 
Best Regards.

**Comment by shyiko** [comment]
@az3 👍 Glad to hear it.
