### ISSUE TITLE
BinaryLogClient calls event listeners before updating client's position

### ISSUE THREAD

**Issue by rhauch** [shyiko/mysql-binlog-connector-java#122]
The BinaryLogClient [processes an event](https://github.com/shyiko/mysql-binlog-connector-java/blob/fb379adeec1648249b25705a6d08974db5533db4/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L748) by first calling the registered event listeners for the event type, and _then_ updating the client's position (i.g., binlog filename & position, GTID set) for that event.

The code may have done it this way because each event header contains the binlog filename and position _of the next event_. This means that because the event handlers are called before the client's binlog filename and position are updated (to the next event), when an event handler is processing an event the client's binlog and filename happen to point to the binlog filename and position _of this event_. 

But GTIDs don't work this way. The `GTID` event that precedes our event of interest has the GTID for _subsequent events_, unlike the event header's binlog filename and position that reflect the _next_ event's position. By updating the client's GTID set _after_ the event listeners are called for the GTID event means that any event listeners reading the client's GTID set see the _GTID set_ before this new transaction, and thus are incorrect.

Fortunately, this behavior affects only the event handlers for `GTID` events.

**Comment by rhauch** [comment]
@shyiko See #125 and #126 for the pull requests for `master` and `0.4.2`, respectively. As mentioned elsewhere, I'm still investigating an issue with code that uses this library and would suggest waiting to release until I've had a chance to do more testing (in case I find additional issues). I'll let you know when I'm confident these changes are the only ones needed. Thanks!

**Comment by shyiko** [comment]
@rhauch 👍 Thank you!

**Comment by rhauch** [comment]
@shyiko, I've not had any other issues. Would appreciate releasing this change -- in 0.4.3? Much appreciated!
