### ISSUE TITLE
Dezer of QueryRowsEvent.

### ISSUE THREAD

**Issue by chenyun** [shyiko/mysql-binlog-connector-java#124]
https://dev.mysql.com/doc/internals/en/rows-query-event.html
The length of RowsQueryEvent is not 1 byte coded， the length is ignored actually!
The body is EOF coded string .

**Comment by shyiko** [comment]
@chenyun Thank you! I'll include the fix in 0.5.1 (which will be released in a few day once PR for #122 is merged in).

**Comment by shyiko** [comment]
@chenyun 0.5.1 released.

**Comment by chenyun** [comment]
@shyiko There is a new problem: If you use a very huge Insert which is larger than MaxPacketSize(16m), The RowsQueryEvent will be splitted into several Packet, so , the underline dezer logic should change a bit.
Here are some details:
   The normal packet is:
    3byte length
    1byte seq
    1byte marker
    PacketBody{
       19 byte header
        header-lengthed byte body
        0 or 4 byte checksum
    } 
In multi packet senario,  ONLY the first packet will contain the 1 byte marker , ONLY the last packet will contain the 0 or 4 byte checksum.

**Comment by shyiko** [comment]
@chenyun I think we're already doing it (https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L731). Or am I missing something?

**Comment by chenyun** [comment]
@shyiko Great! I missed it.
