### ISSUE TITLE
How to get events for specified set of tables

### ISSUE THREAD

**Issue by syed72** [shyiko/mysql-binlog-connector-java#132]
Hi,

Do i have any option or configuration in this connector to collect events only for specified set of tables.

for eg., I have 100 tables and i need only events of 10 tables to be collected. 

Thanks

**Comment by shyiko** [comment]
Hi @syed72. You gonna need to filter out all the unnecessary events. There is no way around it. Table name can be derived by mapping *RowsEventData.tableId to https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/event/TableMapEventData.java#L25.

**Comment by syed72** [comment]
Thanks for quick response...
