### ISSUE TITLE
JsonBinary reads inline literal object properties incorrectly

### ISSUE THREAD

**Issue by cer** [shyiko/mysql-binlog-connector-java#133]
This JSON object had been inserted into MySQL:

```
{"todo":{"complete":false}}
```

JsonBinary cannot correctly parse the binary representation.

According to the comment:

```
*   value-entry ::= type offset-or-inlined-value
 *   // This field holds either the offset to where the value is stored,
 *   // or the value itself if it is small enough to be inlined (that is,
 *   // if it is a JSON literal or a small enough [u]int).
offset-or-inlined-value ::=
 *       uint16 |   // if used in small JSON object/array
 *       uint32     // if used in large JSON object/array
literal ::=
 *       0x00 |   // JSON null literal
 *       0x01 |   // JSON true literal
 *       0x02 |   // JSON false literal
```

However,  this is the code that reads inline literals:

```
   protected void parseBoolean(JsonFormatter formatter) throws IOException {
        Boolean literal = readLiteral();
        if (literal == null) {
            formatter.valueNull();
        } else {
            formatter.value(literal);
        }
    }

protected Boolean readLiteral() throws IOException {
        byte b = (byte) reader.read();
        if (b == 0x00) {
            return null;
        } else if (b == 0x01) {
            return Boolean.TRUE;
        } else if (b == 0x02) {
            return Boolean.FALSE;
        }
        throw new IOException("Unexpected value '" + asHex(b) + "' for literal");
    }
```

It only reads one byte - not uint16 or uint32.

**Comment by shyiko** [comment]
Hi Chris. Please upgrade mysql-binlog-connector-java to 0.5.2 or later (https://github.com/shyiko/mysql-binlog-connector-java/blob/master/changelog.md). I believe this was fixed.

**Comment by cer** [comment]
Thanks for a quick reply. And great work!
We had this problem with 0.6.0
Also, I see the problems when I look at the latest code.

**Comment by shyiko** [comment]
That's weird. I've just tried deserializing `{"todo":{"complete":false}}` (mysql-binlog-connector-java@0.6.0) after it was written to mysql@5.7.15. Everything works fine. (NOTE: `master` is missing some of the code that is part of [0.6.0](https://github.com/shyiko/mysql-binlog-connector-java/blob/0.6.0) (some of the changes are still missing in master)). Can you please double check that you are in fact using 0.6.0?

**Comment by cer** [comment]
With MySQL 5.7.13 `{"todo":{"complete":false}}` deserialized to `{"todo":{"\u0000complete":false}}` and `{"todo": {"order": 0, "title": "1st todo", "completed": false}}` through an exception.

I'll verify that we are using 0.6.0. Thanks

**Comment by shyiko** [comment]
`{"\u0000complete":false}}` - that looks exactly like on the the issues that I fixed in 0.5.2. 

FYI: I tried `{"todo": {"order": 0, "title": "1st todo", "completed": false}}` and I'm not getting any exceptions (same setup).

**Comment by shyiko** [comment]
@cer any updates?

**Comment by cer** [comment]
My developer who encountered this problem was confused. Properly upgrading to 0.6.0 fixed the problem.

**Comment by shyiko** [comment]
@cer Great. Thanks!
