### ISSUE TITLE
Fractional seconds as micros instead of mills

### ISSUE THREAD

**Issue by osheroff** [shyiko/mysql-binlog-connector-java#136]
Hey @shyiko, have gotten back to the maxwell port.  Just a few tests left to go now, but I was chasing down a test that deals with microsecond precision, and found that the binlog-connector does milliseconds and only milliseconds (https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/AbstractRowsEventDataDeserializer.java#L366).   This seems like a sane default, but I don't want to throw away information, especially if people are using DATETIME(6) -- they probably mean it as an ordering column.  

Any possibility you'd accept a patch that allowed the user to configure the connector to output a double (milliseconds + a fraction), or maybe microseconds (as a long)  instead of milliseconds?

**Comment by shyiko** [comment]
Hey Ben. Sure. We could probably add [another flag](https://github.com/shyiko/mysql-binlog-connector-java/commit/340713d7ab831a9b69a8c11fb6f931c006c332a5) to enable microseconds output (personally I would keep value as long regardless of the precision). It seems like a reasonable default for 1.0.0.

If you have patch already - I'd gladly merge it in. If not - I'll do it myself on Saturday. Thank you!

**Comment by osheroff** [comment]
Hi Stanley, that's awesome.  I don't have a patch yet (was looking around, you're releasing off the hotfix branches?), more than happy to pony up the code but if you get to it that's great too.  If I don't see your patch when I get back into the swing of things after the holidays I'll submit one.  Thanks!

-ben

**Comment by shyiko** [comment]
<< you're releasing off the hotfix branches?
yeah... That has to stop at some point :)

**Comment by shyiko** [comment]
[0.7.0 released](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/changelog.md#070---2016-12-24) :christmas_tree:. [DATE_AND_TIME_AS_LONG_MICRO](https://github.com/shyiko/mysql-binlog-connector-java/blob/0.7.0/src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/EventDeserializer.java#L239) was added to support your use case:

```java
EventDeserializer eventDeserializer = new EventDeserializer();
eventDeserializer.setCompatibilityMode(CompatibilityMode.DATE_AND_TIME_AS_LONG_MICRO,
    CompatibilityMode.CHAR_AND_BINARY_AS_BYTE_ARRAY);
binaryLogClient.setEventDeserializer(eventDeserializer);
```
