### ISSUE TITLE
New MySQL binlog event types

### ISSUE THREAD

**Issue by rhauch** [shyiko/mysql-binlog-connector-java#143]
The mysql-binlog-connector library supports all 36 event types according to [official specs](https://dev.mysql.com/doc/internals/en/binlog-event-type.html). However, MySQL-5.7 source code indeed includes [38 event types](https://github.com/mysql/mysql-server/blob/71f48ab393bce80a59e5a2e498cd1f46f6b43f9a/libbinlogevents/include/binlog_event.h#L328), including:

```
VIEW_CHANGE_EVENT= 37,
/* Prepared XA transaction terminal event similar to Xid */
  XA_PREPARE_LOG_EVENT= 38,
```
Looks like MySQL folks haven't updated official docs after made enhancements. Please add support for these event types.

**Comment by rhauch** [comment]
Debezium is currently using 0.5.1 and will likely upgrade to 0.5.2 this week or next. See [our issue](https://issues.jboss.org/browse/DBZ-174) for a bit more information about the context.

**Comment by shyiko** [comment]
Hello Randall. Missing event types added in https://github.com/shyiko/mysql-binlog-connector-java/commit/24c998d91dd27aa4905e2e9743be2c67e4164e45. Let me know if you planned to use them in debezium so that I'd add corresponding `EventDataDeserializer`s.

**Comment by shyiko** [comment]
@rhauch 0.8.0 should became available through Maven Central within the next ~30 minutes or so.

**Comment by rhauch** [comment]
@shyiko Thanks for the quick turnaround. At this time we have no need to actually _use_ the information in these new events.

**Comment by rhauch** [comment]
@shyiko BTW, the releases since 0.5.2 have included some behavioral changes. IIUC, those behavioral changes are all opt-in, meaning unless we choose to use them we shouldn't see any changes to existing behavior (e.g., timestamps). Is that true?

**Comment by shyiko** [comment]
Yes. All of them are opt-in. You should be able to upgrade without any code changes. I try to keep it this way for all releases before 1.0.0.
