### ISSUE TITLE
GTID bookkeeping

### ISSUE THREAD

**Issue by HenryCaiHaiying** [shyiko/mysql-binlog-connector-java#144]
If I want to use the binlog connector to listen on changes from a GTID enabled mysql server, how do I bookkeep the GTIDs my listener has processed.

If I am a mysql slave host, I would have gtid_executed table to keep track all the gtids I've processed.  Do I need to keep a similar persistent storage for my listener code?

Each time when my server restarts, do I need to send a request event to mysql master (is that COM_BINLOG_DUMP_GTID?) with my persisted last_execuited_gtid to ask for resumption of the paused network binlog stream?

For failover, if my listener was previously listening from master A, when A failed and host B was promoted, how do I re-direct my listening to B?  Do I send a COM_BINLOG_DUMP_GTID event to host B to request the binlog stream?

Assume during failover, my listener only executed Tx up to A:4, but master B got one more A:5 and then it starts its own Transactions (B:1, B:2 ...).  When I send the executed GTID (A:4) to host B, will B send me back the stream starting from A:5, B:1, B:2 ...?

**Comment by shyiko** [comment]
Hi. 

If BinaryLogClient is in GTID mode (see https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L303 on how to activate) it will use the gtidSet instead of filename/position to (re)connect. At any point of time, you can get current gtidSet by calling `binaryLogClient.getGtidSet()`.

To answer all other questions - see https://dev.mysql.com/doc/refman/5.6/en/replication-gtids.html.

**Comment by HenryCaiHaiying** [comment]
@shyiko I have a follow-up question, in BinaryLogClient.java#requestBinaryLogStream, for GTID mode, it takes both binlogFileName and gtidSet.  Is this designed for the migration from non-GTID mode to GTID?  During the transition, I supply the previously saved binlogFile/position but no GTID, the mySQL master will send back to me GTID corresponding to that BinLogFile/Position?

**Comment by shyiko** [comment]
@HenryCaiHaiying Too be honest I don't quite remember the exact behavior but luckily I left a note - https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L299 :) So it looks like setGtidSet("") + binlogfilename/position could be used in this way but I would verify it on a live setup (just to be safe). One thing worth mentioning: I don't think PREVIOUS_GTIDS event is taken into account right now (as it was kinda unreliable pre-5.7). It might or might not matter depending on you application logic.
