### ISSUE TITLE
com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException

### ISSUE THREAD

**Issue by j00131120** [shyiko/mysql-binlog-connector-java#147]
please pay attention to solve this issue.

In mysql DB I create talbe as below use  timestamp(3) date type.
CREATE TABLE `t_time` (
  `create_time` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin   
INSERT INTO t_time(create_time) VALUES('2012-00-00 11:00:00.001');

public class TableMapEventDataDeserializer implements EventDataDeserializer<TableMapEventData> {
private int[] readMetadata(ByteArrayInputStream inputStream, byte[] columnTypes) throws IOException {
		int[] metadata = new int[columnTypes.length];
		for (int i = 0; i < columnTypes.length; i++) {
			switch (ColumnType.byCode(columnTypes[i] & 0xFF)) {
			case FLOAT:
			case DOUBLE:
			case BLOB:
				metadata[i] = inputStream.readInteger(1);
				break;
			case BIT:
			case VARCHAR:
			case NEWDECIMAL:
				metadata[i] = inputStream.readInteger(2);
				break;
			case SET:
			case ENUM:
			case STRING:
				metadata[i] = bigEndianInteger(inputStream.read(2), 0, 2);
				break;
			case TIME_V2:
			case DATETIME_V2:
			case TIMESTAMP_V2:
				metadata[i] = inputStream.readInteger(1); // fsp (@see {@link
															// ColumnType})
				break;
			default:
				metadata[i] = 0;
			}
		}
		return metadata;
	}
}

public abstract class AbstractRowsEventDataDeserializer<T extends EventData> implements EventDataDeserializer<T> {
private Serializable deserializeCell(ColumnType type, int meta, int length, ByteArrayInputStream inputStream)
            throws IOException {
        switch (type) {
            case BIT:
                int bitSetLength = (meta >> 8) * 8 + (meta & 0xFF);
                return inputStream.readBitSet(bitSetLength, false);
            case TINY:
                return (int) ((byte) inputStream.readInteger(1));
            case SHORT:
                return (int) ((short) inputStream.readInteger(2));
            case INT24:
                return (inputStream.readInteger(3) << 8) >> 8;
            case LONG:
                return inputStream.readInteger(4);
            case LONGLONG:
                return inputStream.readLong(8);
            case FLOAT:
                return Float.intBitsToFloat(inputStream.readInteger(4));
            case DOUBLE:
                return Double.longBitsToDouble(inputStream.readLong(8));
            case NEWDECIMAL:
                int precision = meta & 0xFF, scale = meta >> 8,
                    decimalLength = determineDecimalLength(precision, scale);
                return toDecimal(precision, scale, inputStream.read(decimalLength));
            case DATE:
                return deserializeDate(inputStream);
            case TIME:
                return deserializeTime(inputStream);
            case TIME_V2:
                return deserializeTimeV2(meta, inputStream);
            case TIMESTAMP:
                return deserializeTimestamp(inputStream);
            case TIMESTAMP_V2:
                return deserializeTimestampV2(meta, inputStream);
            case DATETIME:
                return deserializeDatetime(inputStream);
            case DATETIME_V2:
                return deserializeDatetimeV2(meta, inputStream);
            case YEAR:
                return 1900 + inputStream.readInteger(1);
            case STRING:
                // CHAR or BINARY:
                // because there is no charset info (read: a way to distinguish between these two)
                // we are returning byte[] instead of an actual String
                int stringLength = length < 256 ? inputStream.readInteger(1) : inputStream.readInteger(2);
//                return inputStream.read(stringLength);
                return new String(inputStream.read(stringLength));
            case VARCHAR: // or VARBINARY
            case VAR_STRING:
                int varcharLength = meta < 256 ? inputStream.readInteger(1) : inputStream.readInteger(2);
//                return inputStream.read(varcharLength);
                // TODO 按照默认编码生成字符串
                return new String(inputStream.read(varcharLength));
            case BLOB:
                int blobLength = inputStream.readInteger(meta);
                return inputStream.read(blobLength);
            case ENUM:
                return inputStream.readInteger(length);
            case SET:
                return inputStream.readLong(length);
            default:
                throw new IOException("Unsupported type " + type);
        }
    }}
There is issue about deserializeTimestampV2(meta, inputStream) and deserializeTimestamp(inputStream);

In logically, when insert or update data of timestamp(3). It should be run deserializeTimestampV2,however it execute deserializeTimestamp. So it lead bit stream read error.

function deserialize(ByteArrayInputStream inputStream) of TableMapEventDataDeserializer and UpdateRowsEventData  class have these issues.

**Comment by shyiko** [comment]
@j00131120 please make sure you are using latest mysql-binlog-connector-java release (0.8.1 at this time) . Just tried your example - everything seems to be working fine (MySQL 5.6).
