### ISSUE TITLE
Consider providing a DumpTableCommand

### ISSUE THREAD

**Issue by Aegeaner** [shyiko/mysql-binlog-connector-java#152]
Consider providing a DumpTableCommand which send a COM_TABLE_DUMP to the server to dump a table in detail.

Currently we can only cache the tables infomation when capturing TABLE_MAP events.

[COM_TABLE_DUMP](https://dev.mysql.com/doc/internals/en/com-table-dump.html)

**Comment by Aegeaner** [comment]
sorry, I mean to only dump the table schema, not including the table data.

**Comment by shyiko** [comment]
Hi. Any reasons for not going with `select * from INFORMATION_SCHEMA.COLUMNS` (mentioned in https://github.com/shyiko/mysql-binlog-connector-java#frequently-asked-questions)?
