### ISSUE TITLE
Auto-detect checksum type when reading binary log using BinaryLogFileReader

### ISSUE THREAD

**Issue by shyiko** [shyiko/mysql-binlog-connector-java#160]

**Comment by zzt93** [comment]
Has this issue been solved?

**Comment by shyiko** [comment]
Hi Tony.
Unfortunately, no. [ChecksumType](https://github.com/shyiko/mysql-binlog-connector-java/issues/158#issuecomment-290755649) has to be provided manually.
PR is welcome.

**Comment by zzt93** [comment]
Have any idea about how to implement it? It seems that `FormatDescription` does not have checksum related info and the only way I can come up with now is to try deserialize the first event and If error occur change `ChecksumType`.

**Comment by shyiko** [comment]
https://dev.mysql.com/worklog/task/?id=2540

**Comment by zzt93** [comment]
You may like to review the #219 and give me some suggestions.

**Comment by shyiko** [comment]
Included in [0.17.0](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/CHANGELOG.md#0170---2019-01-07).
