### ISSUE TITLE
READ-COMMITTED generating row-based event data

### ISSUE THREAD

**Issue by simonsharry** [shyiko/mysql-binlog-connector-java#161]
Hello,

I'm using MySql Binlog Connector 0.5.2, with MySql 5.6.13-log.

I'm noticing that, along with binlog_format of MIXED,

    1. If I use a --tx-isoloation value of REPEATABLE-READ, I get the following events:
        QUERY  (sql = "BEGIN")
        QUERY  (sql = "INSERT INTO foo values( ...) ")
        XID

    2. If I use a --tx-isoloation value of READ-COMMITTED, I get the following events:
        QUERY  (sql = "BEGIN")
        TABLE_MAP
        EXT_WRITE_ROWS
        XID

I would like to always get a QUERY event for my insert/update/delete queries so that I can easily extract the sql statement. Is this possible with READ-COMMITTED?

Thanks,
/HS

**Comment by shyiko** [comment]
Hi @simonsharry. You could try enabling https://dev.mysql.com/doc/refman/5.7/en/replication-options-binary-log.html#sysvar_binlog_rows_query_log_events (added in MySQL 5.6.2). I haven't tried it myself though.

**Comment by simonsharry** [comment]
Thanks for your response.

When I enable that, I do get a ROWS_QUERY event, from which I can extract the sql/query. But this has no information about the "database"!

The database name does come as part of a subsequent TABLE_MAP event.

If it can be guaranteed that ROWS_QUERY event will always be immediately followed by a TABLE_MAP event, I can correlate the two events in my code to infer the database name.

Any advice on how to get the database name?

**Comment by shyiko** [comment]
I'm not sure about the order of TABLE_MAP relative to ROWS_QUERY but TABLE_MAP is always gonna be there somewhere (considering that every *RowsEventData event is preceded by TableMapEventData). So yeah, that's the place to get the database name.
