### ISSUE TITLE
request to have release note

### ISSUE THREAD

**Issue by cwei-bgl** [shyiko/mysql-binlog-connector-java#162]
Hi,

Thanks for the great library and effort. I got one request. May we have some note added to future releases? so that we will know what changes a release having made and decide whether to upgrade or not. Thanks.

**Comment by shyiko** [comment]
Hi. Sure. The changelog is included in the repo - https://github.com/shyiko/mysql-binlog-connector-java/blob/master/changelog.md.

**Comment by shyiko** [comment]
Automatic with GitHub releases will be done in https://github.com/shyiko/mysql-binlog-connector-java/issues/164. Cheers!
