### ISSUE TITLE
Read not currently active binlog file

### ISSUE THREAD

**Issue by tatyanka66693** [shyiko/mysql-binlog-connector-java#163]
Is it possible to read not currently active binlog file on a remote database?
I do the following:
```
BinaryLogClient client = new BinaryLogClient("hostname", 3306, "username", "password");
client.registerEventListener(new EventListener() {

    @Override
    public void onEvent(Event event) {
        ...
    }
});
client.setBinlogFilename(binlogFileName);
client.setBinlogPosition(0);
client.connect();
```
if `binlogFileName` is active binlog file - it works, but if `binlogFileName` isn't current binlog file - I get only `ROTATE` event.

**Comment by shyiko** [comment]
Hi Tania.

This is weird. At the very least you should see `FORMAT_DESCRIPTION` event (in addition to `ROTATE`). 

Try executing something similar to
```
show master status;
create database test1;
use test1;
create table t1(id int primary key);
insert into t1 values(1);
flush logs;
show master status;
create table t2(id int primary key);
```
and see whether connecting to binlogfilename (the one shown before flushing logs (with `flush logs`)) is working as expected. Let me know if it doesn't (please specify with version of MySQL in this case).
  
Also, please make sure you are running latest `mysql-binlog-connector-java`,

P.S. You might want to register LifecycleListener (with `client.registerLifecycleListener(...)`) to see what is going on under the hood.

**Comment by tatyanka66693** [comment]
Thank you
