### ISSUE TITLE
Can I use this library with existing, native replication setups?

### ISSUE THREAD

**Issue by pingnikhil** [shyiko/mysql-binlog-connector-java#165]
Hi,

If I understand it right, MySQL Binary Log Connector operates as an independent Replication Slave/Client, and can be safely used in existing, native replication setups without 'disturbing' them in any way.

Thus, if I already have this native replication setup, 
    [ Slave1 ] <-------[ Master ]

then, I assume I would be able to do this,
    [ Slave1 ] <-------[ Master ]-------> [ MySQL Binary Log Connector ]-------> [ my process]

without Slave1's replication getting affected in any way.

Could someone please confirm this?

Thanks,
-Nikhil.

**Comment by shyiko** [comment]
@pingnikhil Correct. Just make sure [server-id](https://dev.mysql.com/doc/refman/5.7/en/replication-options.html#option_mysqld_server-id) used by the slave and [BinaryLogClient](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L239) are different.
