### ISSUE TITLE
Miss a MySQL binlog event type

### ISSUE THREAD

**Issue by stevenczp** [shyiko/mysql-binlog-connector-java#167]
In mysql source code, there is a binlog event type call [TRANSACTION_CONTEXT_EVENT](https://github.com/mysql/mysql-server/blob/71f48ab393bce80a59e5a2e498cd1f46f6b43f9a/libbinlogevents/include/binlog_event.h#L323) between PREVIOUS_GTIDS_LOG_EVENT and VIEW_CHANGE_EVENT

but in mysql-binlog-connector-java, there is no TRANSACTION_CONTEXT_EVENT between PREVIOUS_GTIDS_LOG_EVENT and [VIEW_CHANGE_EVENT](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/event/EventType.java#L190)

this will make mysql-binlog-connector-java can't work on TRANSACTION_CONTEXT_EVENT/VIEW_CHANGE_EVENT/XA_PREPARE_LOG_EVENT   binlog event 

please add this binlog event type, thank you

**Comment by stevenczp** [comment]
first time to pull an issue, no offense, thank you

**Comment by shyiko** [comment]
@stevenczp Thank you so much for reporting this. A new release should be available within half an hour (through Maven Central).
