### ISSUE TITLE
Allow gtids with gap to merge/join

### ISSUE THREAD

**Issue by HenryCaiHaiying** [shyiko/mysql-binlog-connector-java#171]
In our setup from binlog to kafka publish, the GTIDs are not contiguous on kafka side (either because some tables are not published, or different db/tables goes to different topics).  So if we just  use GtidSet.add(gtid), we got many intervals in GtidSet object.

I would like to add a parameter in GtidSet class: gapDistance with the default value of 1.  in GtidSet.UUIDSet.joinAdjacentIntervals, I will use that gapDistance to decide to whether to join two adjacent intervals into one.

Let me know if you like that idea.

**Comment by shyiko** [comment]
Hi @HenryCaiHaiying. 

How about instead of introducing gapDistance we tackle this particular problem in a more generic way: 
- retrieve UUIDSet
- merge intervals you feel like joining together
- replace UUIDSet (using GtidSet::replace(uuidSet) (which would have to be implemented (we could reuse pretty much the same logic as in GtidSet constructor))).

Would this work?

**Comment by HenryCaiHaiying** [comment]
I guess instead of a new replace(uuidSet) method, how about a new method
'putUUIDSet' on GtidSet class:

    putUUIDSet(String uuid, UUIDSet newSet) {
         map.put(uuid, newSet);
    }

**Comment by shyiko** [comment]
UUIDSet has `getUUID(): String` function so there is little point in having `String uuid` argument.

**Comment by HenryCaiHaiying** [comment]
OK.  I guess

public UUIDSet replaceUUIDSet(UUIDSet set) {
    return map.put(set.getUUID(), set);
}

**Comment by HenryCaiHaiying** [comment]
Check PR: https://github.com/shyiko/mysql-binlog-connector-java/pull/172

**Comment by HenryCaiHaiying** [comment]
Thanks for merging in the PR.  Are you going to create 0.12.3 release soon?

**Comment by shyiko** [comment]
@HenryCaiHaiying released as [0.13.0](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/changelog.md#0130---2017-06-04) :balloon:.

**Comment by HenryCaiHaiying** [comment]
Thanks.
