### ISSUE TITLE
mysql subscriber.database.table

### ISSUE THREAD

**Issue by xdfwxg** [shyiko/mysql-binlog-connector-java#179]
Hello, can choose its own definition of mysql table, details of which method

**Comment by shyiko** [comment]
Take a look at https://github.com/shyiko/mysql-binlog-connector-java/issues/132#issuecomment-263493857.  
(feel free to reopen the issue if it's not what you asked)

**Comment by xdfwxg** [comment]
Thank you for your answer.But my question is similar to   
![default](https://user-images.githubusercontent.com/31125447/29500952-4d5c5a08-8657-11e7-8978-194e23c98eb2.png),
I think listening on a mysql table, but not all of them.  What method can let me do it? Can you give an example? Thank you very much

**Comment by xdfwxg** [comment]
Other problems:
![Uploading 图片.png…]()
![Uploading 图片.png…]()
![Uploading 图片.png…]()
This is a correct method of use

**Comment by shyiko** [comment]
There is no way to subscribe to a particular table. You'll need to filter out events based on tableId yourself. See https://github.com/shyiko/mysql-binlog-connector-java/issues/132#issuecomment-263493857 and https://github.com/shyiko/mysql-binlog-connector-java/issues/47#issuecomment-109760177.

**Comment by xdfwxg** [comment]
![default](https://user-images.githubusercontent.com/31125447/29502352-debd43cc-8661-11e7-8515-933168482756.png)
Is that right?
I'm sorry, but I need some details

**Comment by shyiko** [comment]
While this code should* work (if you're only interested in *RowsEventData), it's not correct. You need to match events by tableId - https://github.com/shyiko/rook/blob/master/rook-source-mysql/src/main/java/com/github/shyiko/rook/source/mysql/MySQLReplicationStream.java#L217 + https://github.com/shyiko/rook/blob/master/rook-source-mysql/src/main/java/com/github/shyiko/rook/source/mysql/MySQLReplicationStream.java#L257.
