### ISSUE TITLE
How to read binlog history?

### ISSUE THREAD

**Issue by ChaoShuChina** [shyiko/mysql-binlog-connector-java#180]
Hi!  In the MySQL to another Mysql，I need to read the binlog at once every hour and synchronize it. What do I need to do?
thank you very much!

**Comment by shyiko** [comment]
See https://stackoverflow.com/questions/39386623/mysql-find-bin-log-position-based-on-timestamp.

**Comment by ChaoShuChina** [comment]
Thank you! 
But,I have another question.
How do I read binlog from a fixed point in time instead of reading the whole binlog? Because of the one-time read of the entire binlog, there will be a lot of unnecessary data transmission. And I just want binlog after some time.
My English is very poor. Do you understand what I mean?
Thank you very much！

**Comment by ChaoShuChina** [comment]
@shyiko 
Thank you!
But,I have another question.
How do I read binlog from a fixed point in time instead of reading the whole binlog? Because of the one-time read of the entire binlog, there will be a lot of unnecessary data transmission. And I just want binlog after some time.
My English is very poor. Do you understand what I mean?
Thank you very much！

**Comment by ChaoShuChina** [comment]
@shyiko I want to read the binlog from a certain point in time. Not the whole read, and then the time to judge the filter.What am I going to do?
Thank you！

**Comment by shyiko** [comment]
@ChaoShuChina To my knowledge, there is no way to request binary log using a timestamp. You need either [&lt;binlog filename, position&gt;](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/test/java/com/github/shyiko/mysql/binlog/BinaryLogClientIntegrationTest.java#L645) or GTID (just store either one of them after you disconnect and then set them back before establishing the connection again).
