### ISSUE TITLE
Does this work well in a multi master setup where the binary log files is disabled ?

### ISSUE THREAD

**Issue by vetrigyan** [shyiko/mysql-binlog-connector-java#181]
Hi Stanley,
I just recently came across your project while i was trying to find a solution to listen in realtime for bin log events and post it to appropriate Kafka topics. It looks very interesting. But I need to check one thing with you.
I will end up deploying with one of these cluster solutions - Galera cluster or with Percona XtraDB cluster or Oracle's MySQL Group Replication. The plan is to have multiple masters to share the load for the reads/writes. So does this code work well in each of the below scenarios ?

1.  When used with either of these cluster solutions - Galera, Percona XtraDB or Orachle's MySQL Group Replication ?

2.  Also, how about when binary log files is disabled, but log bin row events is enabled ?

Thank you,
Vetri

**Comment by shyiko** [comment]
Hi @vetrigyan. 

The last time I checked `mysql-binlog-connector-java` worked perfectly fine with Percona XtraDB Cluster (hence Gelara and XtraDB). Can't comment on Oracle's MySQL Group Replication as I'm not really familiar with it (please let me know how it went if you try it).

To answer your second question (provided I understand it correctly): `--log-bin` must be enabled (whether or not you set `binlog_format` to `ROW` doesn't matter (to BinaryLogClient; which is pretty much a MySQL slave as far as MySQL server you connect to is concerned)).

**Comment by vetrigyan** [comment]
Hi Stanley,
Thanks for your reply. 
Regards,
Vetri
