### ISSUE TITLE
How to handle on communication failure

### ISSUE THREAD

**Issue by upendra1024** [shyiko/mysql-binlog-connector-java#184]
I override onCommunicationFailure(BinaryLogClient blc, Exception ex) with listener to handle communication failure.
We have MySQL cluster with virtual IP as slave and master concept.
Replication is happening from the master. And if communication failure happens then have to retry to connect again. on this time if the connection gets success then it will check serverid. if same from previous then no take over else takeover happen.

But here, if still, take over not happen and communication not available with the old server then how to get exit?
onCommunicationFailure(...) how to throw an exception.

**Comment by shyiko** [comment]
Hi.

What do you mean by "it will check serverid"?

If you want to prevent BinaryLogClient from reconnecting (when keepAlive is on (true by default)) in case of communication failure try calling `binaryLogClient.disconnect()` from `onCommunicationFailure`. Let me know if that is not what you are asking. Thanks.

**Comment by upendra1024** [comment]
Thanks a lot for ur quick reply.

As we have 2 mysql servers as master and slave, both have different serverId.
we are finding out through mysql command : select @@server_id
this is to verify : Is take-over happen or not.

if take-over happen, then connecting to same virtual IP will give us different server id.
In that case, On new master, I'll search the last transaction timestamp that got success on the previous master. On new master, I'll take list of binlog(desc order by time of creation). and reach to nearest transaction.. I know there may be duplicates... its ok for us..

I'm going to use binaryLogClient.disconnect()...

**Comment by shyiko** [comment]
I see. Thanks for the explanation!

**Comment by upendra1024** [comment]
Hi,
I already start with binaryLogClient.connect(). that is a blocking call.

onCommunicationFailure, based on serverId change(mysql master takeover), I need to change binlog filename and position and reconnect.

What will you suggest for getting reconnect?

**Comment by shyiko** [comment]
@upendra1024 try [this](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L777) (it's not blocking)

**Comment by upendra1024** [comment]
hi,

I'm getting below exception. but just before that, I wa successfully connected with jdbc to get binlogFilename and position. I'm calling connect with timeout 60 seconds. 

java.util.concurrent.TimeoutException: BinaryLogClient was unable to connect in 60000ms
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:817)
	at com.zoho.mysqlbackup.producer.KafkaBinLogReader$BinLogLifeCycleListener.onCommunicationFailure(KafkaBinLogReader.java:1073)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:921)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:559)
	at com.zoho.mysqlbackup.producer.KafkaBinLogReader.connect(KafkaBinLogReader.java:361)
	at com.zoho.mysqlbackup.producer.KafkaBinLogReader.readBinLog(KafkaBinLogReader.java:345)
	at com.zoho.mysqlbackup.producer.KafkaBinLogReader.run(KafkaBinLogReader.java:226)

**Comment by upendra1024** [comment]
Hi,
Sorry for disturbing a lot :) .
I get fixed my problem.
I'm using blocking binlogClient connect(for me it look easy to handle).

on communication failure, just disconnecting binLogClient.

and where I was started - blocking binlogClient connect, have code something like : 
```

                         client = new BinaryLogClient(sourceDBCluster, 
					Integer.parseInt(dbInfo.getString("dbPort")), 
					dbInfo.getString("dbUser"), dbInfo.getString("dbPasswd"));

			stats = new BinaryLogClientStatistics(client);
			Random r = new Random();
			clientServId = r.nextInt(Integer.MAX_VALUE) + 1;
			client.setServerId(clientServId);
			LOG.info("clientServId: "+client.getServerId());//No I18N
			client.setKeepAliveInterval(TimeUnit.MINUTES.toMillis(keepAliveInterval));

			setReadBinlogPosition();
			client.registerEventListener(new BinLogEventListener()); 			
			client.registerLifecycleListener(new BinLogLifeCycleListener()); 		
			
			while(true)
			{
				connect(); //blocking call
				if(isCommunicationFailure())//on communication failure setting true
				{
					setCommunicationFailure(false);
					handleReconnect();//Handling new mysql master takeover - finding re-setting binlog file and position
				}
				else
				{
					break;
				}
			}
			stopProducerThreads();//stop kafka producer and monitoring threads...
```

And things are working... Thanks a lot.
