### ISSUE TITLE
Is there a special reason to ignore unsigned values of numeric types?

### ISSUE THREAD

**Issue by sungjuly** [shyiko/mysql-binlog-connector-java#188]
Thanks for making a great open source project!  I've encountered unsigned/signed issues when ingesting MySQL binlog. I'm wondering is there a special reason to ignore unsigned values of numeric types? I assume there's additional information of unsigned/signed in table map for sure. It would be great if you share some materials to implement blind spots for this issue.

```
It seems this following method is to map column type from the metadata.
ColumnType.byCode(typeCode)
```

**Comment by shyiko** [comment]
Hi @sungjuly. See https://github.com/shyiko/mysql-binlog-connector-java/issues/104#issuecomment-234991155 (in short, the information needed to understand whether column was signed/unsigned at the time event was generated is missing (in the binary log)).

**Comment by sungjuly** [comment]
@shyiko thanks for clarifying on this!

**Comment by shyiko** [comment]
@sungjuly any time :handshake:
