### ISSUE TITLE
this is  Failed to deserialize

### ISSUE THREAD

**Issue by z589533** [shyiko/mysql-binlog-connector-java#190]
![image](https://user-images.githubusercontent.com/12063612/33534762-9070c8f8-d8e4-11e7-95e0-a36ee7848b39.png)

**Comment by z589533** [comment]
![image](https://user-images.githubusercontent.com/12063612/33534774-ad50d846-d8e4-11e7-96d8-86b63297aca4.png)

**Comment by z589533** [comment]
![image](https://user-images.githubusercontent.com/12063612/33534785-bc93b97c-d8e4-11e7-9b8d-ed797e29478b.png)

**Comment by shyiko** [comment]
@z589533 https://github.com/shyiko/mysql-binlog-connector-java/issues/158#issuecomment-290755649
