### ISSUE TITLE
EventType is always "Query" for mariaDB binlog events

### ISSUE THREAD

**Issue by amca429** [shyiko/mysql-binlog-connector-java#197]
I've set up BinaryLogClient to read and print to screen binlog events from MariaDB version 10.2.7.  Events are received successfully as below.

Event{header=EventHeaderV4{timestamp=1515447662000, eventType=QUERY, serverId=1, headerLength=19, dataLength=162, nextPosition=996, flags=0}, data=QueryEventData{threadId=9, executionTime=0, errorCode=0, database='binlog', sql='insert into campaign (campaign_id, campaign_name) values (2, "Test Campaign2")'}}
Event{header=EventHeaderV4{timestamp=1515448111000, eventType=QUERY, serverId=1, headerLength=19, dataLength=146, nextPosition=1471, flags=0}, data=QueryEventData{threadId=9, executionTime=0, errorCode=0, database='binlog', sql='update campaign set campaign_name = "Test Campaign3" where campaign_name = "Test Campaign2"'}}

My question is: why are they always EventType=QUERY?  I thought inserts (writes) and updates should be of type WRITE_ROWS and UPDATE_ROWS?  Maybe I'm misunderstanding something or this is specific to mariaDB.  Thank you!

**Comment by shyiko** [comment]
@amca429 MariaDB is not currently supported, sorry. As for QUERY vs *_ROWS, chances are --binlog-format is set to STATEMENT (https://dev.mysql.com/doc/refman/5.7/en/binary-log-formats.html).

**Comment by amca429** [comment]
Thanks, starting mysqld with --binlog-format=ROW fixed it.  Regarding MariaDB not being supported, is it a huge risk to continue using this library?  So far everything is working fine.  I was using open replicator previously, but it is now having problem with MariaDB as well, and I'm slowly running out of options.

**Comment by shyiko** [comment]
Using mysql-binlog-connector-java to read events from MariaDB is not safe (mysql-binlog-connector-java is going to fail as soon as one of the https://github.com/shyiko/mysql-binlog-connector-java/pull/50/files#diff-da5972efba95779c6e08fdbcce112b39R193 events is received). 
You could merge https://github.com/shyiko/mysql-binlog-connector-java/pull/50 in to get things rolling but then you'll need to take care of [other issues](https://github.com/shyiko/mysql-binlog-connector-java/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+mariadb).
See https://github.com/shyiko/mysql-binlog-connector-java/pull/50#issuecomment-266228869.

**Comment by amca429** [comment]
Thanks for the reference, I will definitely try them out.
