### ISSUE TITLE
help,help,how to get database's name, tablename ,eventName

### ISSUE THREAD

**Issue by 564064202** [shyiko/mysql-binlog-connector-java#198]
help,help,how to get database's name, tablename ,eventName

  @Override
		    public void onEvent(Event event) {
		       System.out.print(event);
		       ProcessEvent(event);
		    }

**Comment by shyiko** [comment]
@564064202 take a look [here](https://github.com/shyiko/rook/blob/master/rook-source-mysql/src/main/java/com/github/shyiko/rook/source/mysql/MySQLReplicationStream.java#L258).

**Comment by 564064202** [comment]
thanks
