### ISSUE TITLE
Issue with tracking binlogFilename and binlogPosition of an event

### ISSUE THREAD

**Issue by jeyaraj38mit** [shyiko/mysql-binlog-connector-java#199]
We keep track of the binlog filename and binlog offset till which the data has been read in the onEvent method of the event listener. Our code is similar to the one below

public void onEvent(Event event) {
...
String offset = binaryLogClient.getBinlogFilename() + ":" + ((EventHeaderV4) event.getHeader()).getNextPosition();
...
}

We have also set the keepAliveInterval to 5 seconds. So every 5 seconds keepAliveThread submits the ping command and checks whether the connection is lost. If lost, it is terminating the existing connection and creates a new connection again.

We are facing issue with construction of the offset. Because of binlog file rotation, while we were processing the last few events from a binlog file, the binlogFilename in BinaryLogClient is already moved/updated to the next file. We suspect that this could be because of the following.

The problem with the keepAliveThread is that when the connection is terminated, only the socket is closed. So ideally the thread which executes the listenForEventPackets method should not read further more data. Since the data in the buffer of BufferedSocketInputStream is not deleted and as long as there is data in the buffer, this method reads the data and is not exited and it submits the event to the event listener to get processed. 

At the same time the new connection created in another thread, creates a different inputstream and that parallely reads data from the socket and submits the events to the event listener.

So there is a chance of two listenForEventPackets getting executed from two different threads at the same time. If this ended up happening while reading the last few records of a binlog file, one thread might have submitted the event from say binlogfile1 and another thread might have received rotate event and moved on to the next file binlogfile2 which also updates the binlogfilename of the binarylogclient. 

So while processing the event from binlogfile1 in first thread, the construction of offset in the onEvent method I posted above might not work because by the time the offset is constructed, we might be considering the nextPosition from the current event whereas the binlogFilename is updated to the next file by the second thread.

Should not the binlogFilename also be part of the event generated and should not it be part of the PacketChannel class. 

Is there any other way to get the correct binlog file name for the event.

**Comment by shyiko** [comment]
Hi.

> At the same time the new connection created in another thread, creates a different inputstream and that parallely reads data from the socket and submits the events to the event listener.

This shouldn't be happening. https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L744 is expected to block (per https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L1139) until https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L561 is released. 

One possible reason behind the behavior you observe might be `((EventHeaderV4) event.getHeader()).getNextPosition()` part from your snippet. binlogPosition calculation is a little bit more involved - https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L948.

I'd change `public void onEvent(Event event) { ... }` to
```
String eventOffset = binaryLogClient.getBinlogFilename() + ":" + 
    binaryLogClient.getBinlogPosition();
```
\+ register [LifecycleListener::onDisconnect()](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L1191) to get offset of the next event to be processed.

Let me know if this doesn't help. It's always possible something is amiss.

**Comment by gokulakannanm** [comment]
Thanks @shyiko for the response. The issue we are facing as @jeyaraj38mit mentioned is with the library version 0.4.0. I think the blocking change on connect was made post that version. So which version would you suggest us to use? 0.12.1? Is there any non-compatible change in the new version to look forward to?

**Comment by shyiko** [comment]
I try to keep releases backward compatible. You should be able to upgrade to latest [0.13.0](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/changelog.md#0130---2017-06-04) release without any code changes.  
(changelog - https://github.com/shyiko/mysql-binlog-connector-java/blob/master/changelog.md)

(see also https://github.com/shyiko/mysql-binlog-connector-java/issues/178 and https://github.com/shyiko/mysql-binlog-connector-java/issues/136#issuecomment-269108844. unrelated to this ticket but might be of interest considering 0.4.0 -> 0.13.0 upgrade)

**Comment by gokulakannanm** [comment]
Thank you @shyiko !
