### ISSUE TITLE
Update rows without preceding table map

### ISSUE THREAD

**Issue by zzt93** [shyiko/mysql-binlog-connector-java#200]
<img width="547" alt="2018-01-24 5 14 48" src="https://user-images.githubusercontent.com/5842389/35324042-7e7e4954-012a-11e8-8b17-dd00e58febe1.png">
<img width="449" alt="2018-01-24 5 15 04" src="https://user-images.githubusercontent.com/5842389/35324044-7ed4e4a8-012a-11e8-910e-34ac07132111.png">

As you can see from above image, is this the bug of MySQL or 
```
TABLE_MAP_EVENT

Used for row-based binary logging. This event precedes each row operation event. 
```
my understanding for this sentence is wrong?

**Comment by shyiko** [comment]
Hi @zzt93 

It should be "This event precedes row operation event(s)." (one or more). 
To get a better idea - run https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/test/java/com/github/shyiko/mysql/binlog/BinaryLogFileReaderIntegrationTest.java#L47 and log events (e.g. `System.out.println(event.getHeader().getEventType());`). Output will be similar to:

```
...
TABLE_MAP
WRITE_ROWS
WRITE_ROWS
WRITE_ROWS
TABLE_MAP
WRITE_ROWS
WRITE_ROWS
XID
QUERY
TABLE_MAP
WRITE_ROWS
XID
```

**Comment by zzt93** [comment]
Ok, thanks for correct me.
