### ISSUE TITLE
Failed to deserialise data for only EXT_UPDATE_ROWS

### ISSUE THREAD

**Issue by architsingla13** [shyiko/mysql-binlog-connector-java#201]
Hi,

Getting 

ERROR  [] -  Ver:1  HeapInfo:(14316732416,9297723392,9024488024) MySQLSlave::onCommunicationFailure::com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1517385965000, eventType=EXT_UPDATE_ROWS, serverId=1601, headerLength=19, dataLength=7977, nextPosition=665062370, flags=0}
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:216)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:184)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:890)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:559)
	at net.media.myredis.service.MySQLSlave.run(MySQLSlave.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:190)
	at java.io.InputStream.read(InputStream.java:170)
	at java.io.InputStream.skip(InputStream.java:224)
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.skipToTheEndOfTheBlock(ByteArrayInputStream.java:216)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:212)

i was not able to find no such pattern why the error is being thrown.
Went through - https://github.com/shyiko/mysql-binlog-connector-java/issues/68,
https://github.com/shyiko/mysql-binlog-connector-java/issues/61,
https://github.com/shyiko/mysql-binlog-connector-java/issues/90

Thanks in advance

**Comment by architsingla13** [comment]
Have also tried the latest version 0.13.0,
Earlier was using 0.12.1

**Comment by shyiko** [comment]
Hi @architsingla13. Check also https://github.com/shyiko/mysql-binlog-connector-java/issues/21. If it's not https://github.com/shyiko/mysql-binlog-connector-java/issues/21#issuecomment-42927142 nor https://github.com/shyiko/mysql-binlog-connector-java/issues/90#issuecomment-196918301 then I'll need a slice of the binary log section where you get EXT_UPDATE_ROWS (binarylog file will do) (or some way to reproduce the problem). Thanks.

**Comment by architsingla13** [comment]
On manually assigning a different serverid to BinlogClient (though there is only one client),
and setKeepAliveInterval and connect time as mentioned in post #21 which was earlier set to defaults.

gettting this error now - 

com.github.shyiko.mysql.binlog.network.ServerException: log event entry exceeded max_allowed_packet; Increase max_allowed_packet on master

**Comment by architsingla13** [comment]
This is the part of binlog i can share - 

#180201  6:17:38 server id 1601  end_log_pos 394636803 CRC32 0xb02acd26 	Update_rows: table id 914
# at 394636803
#180201  6:17:38 server id 1601  end_log_pos 394644903 CRC32 0x2df4be01 	Update_rows: table id 914
# at 394644903
#180201  6:17:38 server id 1601  end_log_pos 394652885 CRC32 0xf0d77312 	Update_rows: table id 914
# at 394652885
#180201  6:17:38 server id 1601  end_log_pos 394661069 CRC32 0xa6284fd7 	Update_rows: table id 914
# at 394661069
#180201  6:17:38 server id 1601  end_log_pos 394668931 CRC32 0x408045a9 	Update_rows: table id 914
# at 394668931
#180201  6:17:38 server id 1601  end_log_pos 394676927 CRC32 0x76cf34b2 	Update_rows: table id 914
# at 394676927
#180201  6:17:38 server id 1601  end_log_pos 394684993 CRC32 0x9cf816bc 	Update_rows: table id 914
# at 394684993
#180201  6:17:38 server id 1601  end_log_pos 394692875 CRC32 0x5ba26dc9 	Update_rows: table id 914
# at 394692875
#180201  6:17:38 server id 1601  end_log_pos 394700609 CRC32 0x22711411 	Update_rows: table id 914
# at 394700609
#180201  6:17:38 server id 1601  end_log_pos 394708461 CRC32 0x55517b7e 	Update_rows: table id 914
# at 394708461
#180201  6:17:38 server id 1601  end_log_pos 394716671 CRC32 0xd09bd29d 	Update_rows: table id 914
# at 394716671
#180201  6:17:38 server id 1601  end_log_pos 394724775 CRC32 0x3c3d22e5 	Update_rows: table id 914
# at 394724775
#180201  6:17:38 server id 1601  end_log_pos 394732947 CRC32 0x3d0ca549 	Update_rows: table id 914
# at 394732947
#180201  6:17:38 server id 1601  end_log_pos 394740923 CRC32 0x8620e56b 	Update_rows: table id 914
# at 394740923
#180201  6:17:38 server id 1601  end_log_pos 394749089 CRC32 0xb5a2279f 	Update_rows: table id 914
# at 394749089
#180201  6:17:38 server id 1601  end_log_pos 394756913 CRC32 0xd3586640 	Update_rows: table id 914
# at 394756913
#180201  6:17:38 server id 1601  end_log_pos 394765045 CRC32 0x24b8d397 	Update_rows: table id 914
# at 394765045
#180201  6:17:38 server id 1601  end_log_pos 394773173 CRC32 0xd5c351fe 	Update_rows: table id 914
# at 394773173
#180201  6:17:38 server id 1601  end_log_pos 394781123 CRC32 0x073c4e89 	Update_rows: table id 914
# at 394781123
#180201  6:17:38 server id 1601  end_log_pos 394789181 CRC32 0x5736cfff 	Update_rows: table id 914
# at 394789181
#180201  6:17:38 server id 1601  end_log_pos 394797061 CRC32 0x49759b42 	Update_rows: table id 914
# at 394797061

and error was - 
mysql-bin.018621::394716671 com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1517465858000, eventType=EXT_UPDATE_ROWS, serverId=1601, headerLength=19, dataLength=8085, nextPosition=394724775, flags=0}

The thing error does not come when the app restarts from same position.
Happens frequently.

**Comment by Shikhar-S** [comment]
@shyiko Any update on this issue?

**Comment by shyiko** [comment]
@Shikhar-S in order to fix the problem I need the binlog file (in binary form, something you can open with [BinaryLogFileReader](https://github.com/shyiko/mysql-binlog-connector-java#reading-binary-log-file)). Otherwise I can only guess.
