### ISSUE TITLE
How to read original format of the file

### ISSUE THREAD

**Issue by issacbalaji** [shyiko/mysql-binlog-connector-java#203]
How to read the original formate as it is in binlog file in the mysql please any suggestions

**Comment by shyiko** [comment]
@issacbalaji can you please be a little bit more specific? What format?

**Comment by issacbalaji** [comment]
I mean before deserialization how it is in binlog , the same format

**Comment by shyiko** [comment]
@issacbalaji something like https://github.com/shyiko/mysql-binlog-connector-java/issues/33#issuecomment-86650863?

**Comment by issacbalaji** [comment]
Can you please suggest which object to be printed in which line
