### ISSUE TITLE
unsigned int deserialize error

### ISSUE THREAD

**Issue by ShaoxiongTang** [shyiko/mysql-binlog-connector-java#205]

**Comment by shyiko** [comment]
Can you please elaborate / provide steps to reproduce?

**Comment by ShaoxiongTang** [comment]
hi, shyiko:

you can create table like follow sql and insert one record with null primary key.  you will see an negative primary key in binlog. 
CREATE TABLE `test_tb` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `data` varchar(64) default '' NOT NULL,
  PRIMARY KEY (`id`),
) ENGINE=InnoDB AUTO_INCREMENT=4294967295 DEFAULT CHARSET=utf8;

To fix this problem, we open two channel. one is for binlog stream and , another is used to fetch table meta, use query like 'desc table' query.
