### ISSUE TITLE
Reset binlog file name on connection lost

### ISSUE THREAD

**Issue by vuckooo** [shyiko/mysql-binlog-connector-java#207]
Hi,

First, I will explain the architecture of the system.

We use [Vitess](https://vitess.io/) as primary storage and we chose **Debezium** for the CDC, it simplifies data stream to **Kafka**.

Vitess enables MySql horizontal scaling and all Mysql instances in the cluster have a unique binlog file name.

Here is an example:

Imagine you have 3 instances, each have a unique identifier (100, 101, 102). Binlog file will have a different name (vt_100.index, vt_101.index, vt_102.index). Instances are in master-slave replication mode.

In front of Debezium we have set **HAProxy** to get HA in case of Mysql instance crash and  Debezium and **BinaryLogClient** are connected to it.

And here is a problem :)

In the testing phase we noticed that when the Mysql instance crashes and **BinaryLogClient** uses this instance for binlog parsing. **BinaryLogClient** will try to make a new connection.
HAProxy will forward the connection to another Mysql instance, but there is another name for binlog file.
The **BinaryLogClient** uses the name of the binlog file which is currently in the memory (binlog file name from the crashed instance), and the new connection will not be made because different binlog file name is used on the new instance.

Suggestions:

1. Debezium and third party libraries set binlog file name to NULL on onDisconnect event. This is already supported by this library, but it’s not a clean solution.
2. Set binlog file name to null inside **BinaryLogClient** for every disconnect event. Promote this behaviour as default.
3. Enable the configuration option within the **BinaryLogClient** class. Something like **RefreshBinlogFileNameOnDisconnect**, bool property that will allow building logic in case of connection lost.

My favorite is option 3.

Our team is willing to do the implementation, we just need agreement about the best way.
Also maybe we didn’t see something obvious and issue can be closed :)

**Comment by shyiko** [comment]
Hi.

Resetting binlog filename/position on disconnect to NULL is a potentially disastrous behavior. In doing so you risk skipping chunks of the binlog, receiving events out of order, etc. I guess you could use [ServerException::errorCode](https://github.com/shyiko/mysql-binlog-connector-java/blob/eead0ec2338f7229ba74a7a04188f4967f13d4b7/src/main/java/com/github/shyiko/mysql/binlog/network/ServerException.java#L37) to build a condition for such behavior but I'm not sure this is something that belongs in mysql-binlog-connector-java.

@rhauch WDYT? Is this something Debezium could do / is doing?

**Comment by vuckooo** [comment]
Then mysql-binlog-connector-java library is discouraged to use in case of MySql Ha setup and the proxy in front of the cluster?

This case with Vitess binlog names where every instance has different basename, but most of cases don’t, so maybe somebody uses library with proxy and on reconnect current binlog file name is used but connection is made on different instance.

Maybe I made wrong conclusion from your comment. :)

We need HA solution and connection to one of the servers from the cluster is not an option.

Every suggestion will be helpful.

**Comment by vuckooo** [comment]
What we want to accomplish is a new fetching binlogfile name in case of connection lost.
So you think this can lead system to inconsistent state?

**Comment by shyiko** [comment]
@vuckooo What I meant was mysql-binlog-connector-java is not intended to be used "as-is" in HA environments like yours. You can build a solution on top of mysql-binlog-connector-java by leveraging ServerException::errorCode and onDisconnect, but this is not something available out-of-the-box (there are just too many variables).

**Comment by vuckooo** [comment]
@shyiko Thanks, I've figured out how to explicitly set basename for binlog.
Thanks for time and effort
