### ISSUE TITLE
Can binlogPositions determine the current Bin-log location?

### ISSUE THREAD

**Issue by ChaoShuChina** [shyiko/mysql-binlog-connector-java#215]
Hello Shyiko!
I want to synchronize the mysql database with bin-log in the main-standby mode. This requires the location of the last bin-log event. Should I use client.getBinlogPosition() or client.getGtidSet()? What is the difference between getBinlogPosition and getGtidSet?
Thank you! Thank you for helping the rookie!
Thank you, and thanks for google translation!！

**Comment by ChaoShuChina** [comment]
@shyiko

**Comment by chenGit1763113879QQ** [comment]
binlog 文件名 和 stop position

**Comment by chenGit1763113879QQ** [comment]
Synchronous binlog file name and stop position

**Comment by shyiko** [comment]
`binlogFilename`/`binlogPosition` = [Binary Log File Position Based Replication](https://dev.mysql.com/doc/refman/8.0/en/replication-howto.html)
`gtidSet` = [Replication with Global Transaction Identifiers](https://dev.mysql.com/doc/refman/8.0/en/replication-gtids.html) 

NOTE: it's perfectly legal to use `binlogFilename`/`binlogPosition` even if --gtid-mode=ON,  
the opposite (`gtidSet` + --gtid-mode=OFF) is not.
