### ISSUE TITLE
Frequent Mysql Disconnections

### ISSUE THREAD

**Issue by barani-fp** [shyiko/mysql-binlog-connector-java#216]
ERROR f.p.f.r.reader.task.StreamListener - On communication failure
com.github.shyiko.mysql.binlog.network.ServerException: could not find next log; the first event 'x-mysql-470125-bin.000063' at 745990074, the last event read from '/var/log/mysql/x-mysql-470125-bin.000063

is it anything with blocking mode??

**Comment by shyiko** [comment]
Make sure you are connecting to the same server (not HAProxy) using binlogFilename/binlogPosition that exists. This has nothing to do with blocking mode.

**Comment by barani-fp** [comment]
Hi,
Forgot to mention this is intermittent error.This failure will be raised and no stream will be processed , but when in restart it works fine(so filename/position exists) and it occurs sometimes again (once in a week may be ).

**Comment by codeex** [comment]
Same question, The Error info is  MySql server error: RUNNING_ERROR: MYSQL_006 - MySql server error: could not find next log; the first event 'mysql-bin.003474' at 162593114, the last event read from '/home/mysql/data3006/mysql/mysql-bin.003474' at 162593256, the last byte read from '/home/mysql/data3006/mysql/mysql-bin.003474' at 162593256
