### ISSUE TITLE
Long text become `BLOB(-4)`

### ISSUE THREAD

**Issue by zzt93** [shyiko/mysql-binlog-connector-java#220]
The following is the table creation clause:
```
  content             LONGTEXT                            NULL,
```
But when I receive the binlog, it become the `Protocol::MYSQL_TYPE_BLOB`, is that normal?

**Comment by shyiko** [comment]
[It is](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/test/java/com/github/shyiko/mysql/binlog/BinaryLogClientIntegrationTest.java#L343) (list of all possible column types - [ColumnType](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/ColumnType.java#L55)). [CompatibilityMode.CHAR_AND_BINARY_AS_BYTE_ARRAY](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/EventDeserializer.java#L282) might be of interest (turned on in [BinaryLogClientIntegrationTest](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/test/java/com/github/shyiko/mysql/binlog/BinaryLogClientIntegrationTest.java#L127)).
