### ISSUE TITLE
Questions about how to cache mysqlbinlog-event

### ISSUE THREAD

**Issue by ChaoShuChina** [shyiko/mysql-binlog-connector-java#222]
Hello！shyiko
I now use mysql-binlog-connector-java to achieve mysql2mysql data synchronization, the steps are as follows:
1. Full migration, transfer the data of the main library all at once to the backup repository.
2. Real-time synchronization of changes to the main library to the backup library.
The main function I have already achieved, but in the process of full migration, the main library changes I can not capture the cache. Do you have any suggestions?
Thank you very much!

God blesses people who are willing to answer questions. Pretty girls also like people who are willing to answer questions!
@shyiko
                                                                                                                   Shu.Chao from China

**Comment by shyiko** [comment]
Are you asking about https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L258 or https://github.com/shyiko/mysql-binlog-connector-java/issues/33#issuecomment-86650863? If not - please clarify.

**Comment by ChaoShuChina** [comment]
thank you! With your help, I think I have found the answer！
