### ISSUE TITLE
Commit or Rollback

### ISSUE THREAD

**Issue by shellitaboola** [shyiko/mysql-binlog-connector-java#223]
Hi
After a row mutation event occurs, how do I know if it was committed or rolled back?

Do I need to wait for an XID event?
Is there a way to only get committed events?
Thanks

**Comment by shyiko** [comment]
Hi. 

See [EventType.XID](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/event/EventType.java#L101) javadoc.

> Is there a way to only get committed events?

You'll have to filter out rollbacked transactions on your own. mysql-binlog-connector-java emits events "as is" (nothing is filtered out).
