### ISSUE TITLE
What is the difference between gtidset and binlogposition?

### ISSUE THREAD

**Issue by ChaoShuChina** [shyiko/mysql-binlog-connector-java#225]
hello! shyiko
    After restarting the connection, I want to continue reading historical events from the last position.
client.setBinlogPosition or client.setGtidSet Which one is suitable?
my code is as follows: But the result is wrong:

    client = new BinaryLogClient(host, port,username,password);
    client.setBinlogPosition(binlogPosition);//Not working. After the client restarts, it does not read events during the stop
    client.setGtidSet(gtidToDB );//Last gtid before stopping the client, the last successful sync position
    client.registerEventListener(new BinaryLogClient.EventListener() {
    public void onEvent(Event event) {
        String gtidToDB = client.getGtidSet();//getGtidSet()=null
        //Write gtidToDB to the database
    .......
    }
Can you give me some sample code?
Thank you!

**Comment by ChaoShuChina** [comment]
@shyiko

**Comment by wudan3551** [comment]
i found the same problem，so ，the binlog server will remember last consume position and ignore setBinlogPosition parameter ? @shyiko

**Comment by wudan3551** [comment]
i just solve this problem by specify binlogFileName (client.setBinlogFilename) ，and please close the issue @ChaoShuChina

**Comment by shyiko** [comment]
[GTID vs binlog filename/position](https://dev.mysql.com/doc/refman/5.6/en/replication-gtids.html) (the answer to the original question: both methods are suitable depending on the use case)
