### ISSUE TITLE
[Question] Status of integration tests

### ISSUE THREAD

**Issue by jonahgeorge** [shyiko/mysql-binlog-connector-java#235]
Hey @shyiko,

First of all, thank you a ton for providing this library. 

I'm curious about the status of the integration tests in this repo. Both on HEAD and at the latest tagged release, I'm unable to get a clean test run with `mvn clean verify` and I'm curious if this is expected or not. 

Additionally, would you be interested in adding the integration test suite to the CI? I'm not sure if this is possible via Travis; however, CircleCI has support for docker-compose which would allow for multiple MySQL containers to be run during tests. If so, this is something I could likely contribute.

**Comment by shyiko** [comment]
Hi @jonahgeorge. 

That's weird. I just tried `./mvnw clean verify` (`master` branch) and got `BUILD SUCCESS`. Any chance you can provide a build log?

> Additionally, would you be interested in adding the integration test suite to the CI?

Absolutely. I'd be more than happy to merge such PR in (CI choice does not matter).

**Comment by jonahgeorge** [comment]
Here's the build log:
https://gist.github.com/jonahgeorge/966d4d5c7ed0fd1a2ef42fca2a61427b

I'll see about getting that integration setup

**Comment by jonahgeorge** [comment]
Please note that using a Dockerized environment leads to similar failures:
https://gist.github.com/jonahgeorge/792220e80152a2e6189589570e446345

**Comment by shyiko** [comment]
Confirmed (reproducable using docker-compose.yaml provided in https://gist.github.com/jonahgeorge/792220e80152a2e6189589570e446345). Thank you :bowing_man:.

**Comment by shyiko** [comment]
@jonahgeorge fixed in master.
