### ISSUE TITLE
No field name in TABLE_MAP_EVENT?

### ISSUE THREAD

**Issue by e7868a** [shyiko/mysql-binlog-connector-java#24]
Hi.

This is not a problem about 'mysql-binlog-connector-java'.

I just find out that there is no field name in **TableMapEventData**. how can i regenerate the SQL from WRITE_ROWS,UPDATE_ROWS,DELETE_ROWS.or there is other method to update slave mysql database?

Thanks for help.

**Comment by spccold** [comment]
this dosen't work when mysql-binlog-connector-java have a large lag, because mysql binlog is old, but metadata is latest

**Comment by poojariVyankatesh** [comment]
Hi, 
I want to implement the WRITE_ROWS but I'm not know how to implement it.
