### ISSUE TITLE
Issue with mysql server - binlog_row_image=full not always honoured for binrow_format=MIXED

### ISSUE THREAD

**Issue by upendra1024** [shyiko/mysql-binlog-connector-java#249]
First, thanks a lot for mysql-binlog-connector-java library.
We are using this to replicate mysql data to kafka and hadoop setup.

We have mysql server - MySQL 5.7.18.
And facing a bug wth mysql server : 

> binlog_row_image=full not always honoured for binrow_format=MIXED.

I have reported this bug with percona support and they have reported this to upstream : 
https://bugs.mysql.com/bug.php?id=93423

I'm not sure how long time it will take to get fixed, and then my datacenter needs to upgrade with the latest one.

Is it possible to get the ordinal position of each column with mysql-binlog-connector-java library?
So I'll find out what are the columns are missing by comparing with table schema details.
After knowing this I can prepare kafka message with missing column and its default value.

If there is any other way to handle this, then pls let me know.

Thanks.

**Comment by bluebike** [comment]
Well... why to use binrow_format=MIXED anyway? 
Doesn't really make sense if you are trying to read events to kafka?
DDL + Grants are of course statements (QUERY events)... but????

**Comment by upendra1024** [comment]
@bluebike
Sorry for late reply...

We have master, slave and secondary-slave architecture for every single mysql server in for the service.
we use fail-over service to monitor, takeover and bind cluster IP with current master.

there is one special table that we keep updating every 5 seconds. for this table, we need events as statement and will get use while take over.

We are checking GTID approach to solve this mysql HA requirement.
Then MIXED format is not required.
