### ISSUE TITLE
Do not track binlogFilename/binlogPosition when GtidSet is set

### ISSUE THREAD

**Issue by shyiko** [shyiko/mysql-binlog-connector-java#254]
https://github.com/shyiko/mysql-binlog-connector-java/pull/250#issuecomment-453372091

NOTE: having binlogFilename/binlogPosition avoids scanning unnecessary logs so check what are the options before blindly disabling binlogFilename/binlogPosition tracking.

**Comment by osheroff** [comment]
hey @shyiko this is actually pretty nasty / dangerous; see 

https://github.com/zendesk/maxwell/issues/1129#issuecomment-454766182
and
https://github.com/zendesk/maxwell/pull/1192

turns out that unless we jump through a lot of hoops to reconnect in GTID land, things go quite wrong.

**Comment by shyiko** [comment]
Fixed in [0.18.0](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/CHANGELOG.md#0180---2019-01-21).
