### ISSUE TITLE
setBinlogPosition does not read events that happened when the server was down

### ISSUE THREAD

**Issue by tonikarhu** [shyiko/mysql-binlog-connector-java#257]
I want to continue reading the binlog from the position that it read from last before a reboot.

I did something like this it saves the position in the filesystem and retrieves it when you reboot, but it doesn't work am i doing it wrong or is it not possible to do that??:

 BinaryLogClient client =
                new BinaryLogClient("localhost", 3306, USER, PASS);
        Long binLogPosition = loadBinLogPosition();
        if(binLogPosition!=null) {
            System.out.println("Setting bin log position: "+binLogPosition);
            client.setBinlogPosition(binLogPosition);
        }

**Comment by shyiko** [comment]
@tonikarhu make sure to `setBinlogFilename()` & `setBinlogPosition()` (both of them)
