### ISSUE TITLE
Preserve comments in MySQL queries

### ISSUE THREAD

**Issue by rphv** [shyiko/mysql-binlog-connector-java#269]
Please see this thread https://groups.google.com/forum/#!topic/debezium/o355nA66SdE
for info re: how I landed here.

I'm writing some additional transaction information to the MySQL binlog via a comment appended to the SQL statement. I've enabled the MySQL sysvar binlog_rows_query_log_events so the SQL statement is written to the binlog along with the row-based log info (see example below).

However, it appears that the mysql-binlog-connector-java SQL parser (as used by Debezium) strips these comments from the statement.

Is it feasible to preserve these comments (as they appear in the binlog) instead of stripping them?

MySQL binlog example:
```
BEGIN
/*!*/;
# at 961
#190320 17:02:04 server id 419  end_log_pos 1085        Rows_query
# INSERT INTO my_table VALUES (999, 888, 777, 666) /* ADDITIONAL TRANSACTION INFORMATION */ #
# at 1085
#190320 17:02:04 server id 419  end_log_pos 1145        Table_map: `mydb`.`my_table` mapped to number 27176
# at 1145
#190320 17:02:04 server id 419  end_log_pos 1187        Write_rows: table id 27176 flags: STMT_END_F
### INSERT INTO `mydb`.`my_table`
### SET
###   @1=999 /* INT meta=0 nullable=0 is_null=0 */
###   @2=888 /* INT meta=0 nullable=0 is_null=0 */
###   @3=777 /* TINYINT meta=0 nullable=0 is_null=0 */
###   @4=666 /* TINYINT meta=0 nullable=0 is_null=0 */
# at 1187
#190320 17:02:24 server id 419  end_log_pos 1214        Xid = 17397187
COMMIT/*!*/;
SET @@SESSION.GTID_NEXT= 'AUTOMATIC' /* added by mysqlbinlog */ /*!*/;
DELIMITER ; @ #```

**Comment by shyiko** [comment]
Sorry for the delay @rphv but mysql-binlog-connect-java does not remove the comments (see https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/QueryEventDataDeserializer.java#L37). I'd recommend checking on Debezium side.

**Comment by rphv** [comment]
Thanks for taking a look @shyiko. I originally opened the issue with Debezium and was directed here.

Any idea why the Debezium side seems to think this information is not returned by the binlog client?

Here's the issue I opened: https://issues.jboss.org/browse/DBZ-1239

**Comment by shyiko** [comment]
@rphv That must be a mistake. I tried executing `create database /* test */ mbcj_test` and got 
`INFO: Received Event{header=EventHeaderV4{timestamp=1557899545000, eventType=QUERY, serverId=1, headerLength=19, dataLength=101, nextPosition=509, flags=8}, data=QueryEventData{threadId=3, executionTime=0, errorCode=0, database='mbcj_test', sql='create database /* test */ mbcj_test'}}` (from mysql-binlog-connect-java).

**Comment by rphv** [comment]
@shyiko Thank you again for checking this out. Sorry to trouble you with this.

**Comment by shyiko** [comment]
No worries!
