### ISSUE TITLE
FK relationship

### ISSUE THREAD

**Issue by nrajagopal** [shyiko/mysql-binlog-connector-java#27]
How to get notification for tables having fk realtionship like on delete cascade  etc..

**Comment by shyiko** [comment]
Hello. 

Short answer: you don't. You won't find anything in the binary log to help you with that. 
But... you can always [read the schema in](https://github.com/shyiko/mysql-binlog-connector-java/issues/24#issuecomment-43752483) and watch for changes on table(s) defining FKs. For example, in case of ON DELETE CASCADE (let's say, table "a" references table "b") you could listen for EXT_DELETE_ROWS event on "a" and use that to get an id of linked "b" record.
