### ISSUE TITLE
How to read binary log if give pathway

### ISSUE THREAD

**Issue by hafiz013** [shyiko/mysql-binlog-connector-java#270]
Hi, I new here, I am looking for read binary file for example it given already path of binary log 
"/public_html/makkohijaulog" and cridential log in as below code

`BinaryLogClient client1 = new BinaryLogClient("90.8.190.300", 120, "makkohijau", "otakoudang");

        EventDeserializer eventDeserializer = new EventDeserializer();
        eventDeserializer.setCompatibilityMode(
                EventDeserializer.CompatibilityMode.DATE_AND_TIME_AS_LONG,
                EventDeserializer.CompatibilityMode.CHAR_AND_BINARY_AS_BYTE_ARRAY
        );
        client1.setEventDeserializer(eventDeserializer);
        client1.registerEventListener(new BinaryLogClient.EventListener() {

            @Override
            public void onEvent(Event event) {

            }
        });
        try {
            client1.connect();
        } catch (IOException e) {
            e.printStackTrace();
        }`

Reading binary file should be like

0, 9.0, N\B

**Comment by shyiko** [comment]
See https://github.com/shyiko/mysql-binlog-connector-java#reading-binary-log-file.
