### ISSUE TITLE
Reading a string using the default encoding, instead of using the columns encoding

### ISSUE THREAD

**Issue by baraklu** [shyiko/mysql-binlog-connector-java#276]
Hey 

We encountered an issue with multi-language strings read from the binlog. 
eventually we traced the issue to the point where a deserializing a string from the binlog uses the java default charset and not the correct one of the column.  

attached the relevant row. 
https://github.com/shyiko/mysql-binlog-connector-java/blob/d466f72f083cf6e1c17d2d481131fa2d68f8b26f/src/main/java/com/github/shyiko/mysql/binlog/io/ByteArrayInputStream.java#L66

**Comment by shyiko** [comment]
yeah, this is a now issue - see https://github.com/shyiko/mysql-binlog-connector-java/blob/d466f72f083cf6e1c17d2d481131fa2d68f8b26f/src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/AbstractRowsEventDataDeserializer.java#L364. please set CHAR_AND_BINARY_AS_BYTE_ARRAY as specified in https://github.com/shyiko/mysql-binlog-connector-java#tapping-into-mysql-replication-stream.
