### ISSUE TITLE
How to stop the event.

### ISSUE THREAD

**Issue by c2ch** [shyiko/mysql-binlog-connector-java#281]
client.connect() is blocking.
I want to stop the connect.So I use client.disconnect(),but it doesn't work.
![image](https://user-images.githubusercontent.com/35028011/58862327-0de01c00-86e3-11e9-8e76-c3c43abaea12.png)
![image](https://user-images.githubusercontent.com/35028011/58862344-15072a00-86e3-11e9-95b3-da795b5a3360.png)
![image](https://user-images.githubusercontent.com/35028011/58862344-15072a00-86e3-11e9-95b3-da795b5a3360.png)
the result is connect is still alive.

**Comment by ahmedahamid** [comment]
@c2ch `BinaryLogClient.connect()` is a blocking method, i.e. calling `Binlog.connect()` will never return as long as you're connected to the server and you won't have a chance to call `Binlog.disconnect()`.

You can use `BinaryLogClient.connect(timeout)` instead; it'll connect and return so you can call disconnect whenever you need.
