### ISSUE TITLE
Ability to deserialize TABLE_MAP and ROTATE events to byte arrays

### ISSUE THREAD

**Issue by gostrc** [shyiko/mysql-binlog-connector-java#29]
Related to https://github.com/shyiko/mysql-binlog-connector-java/issues/28 since the library depends on those being deserialized to a specific type.

**Comment by shyiko** [comment]
I think you can try something similar to:

```java
public class CustomRotateEventData extends RotateEventData {

    private byte[] data;

    public byte[] getData() {
        return data;
    }

    public void setData(byte[] data) {
        this.data = data;
    }
}

public class CustomRotateEventDataDeserializer extends RotateEventDataDeserializer {

    @Override
    public RotateEventData deserialize(ByteArrayInputStream inputStream) throws IOException {
        byte[] data = inputStream.read(inputStream.available());
        RotateEventData eventData = super.deserialize(new ByteArrayInputStream(data));
        CustomRotateEventData result = new CustomRotateEventData();
        result.setData(data);
        result.setBinlogPosition(eventData.getBinlogPosition());
        result.setBinlogFilename(eventData.getBinlogFilename());
        return result;
    }
}

eventDeserializer.setEventDataDeserializer(EventType.ROTATE, new CustomRotateEventDataDeserializer());
```

Obviously, the same has to be done for TableMapEventData.

**Comment by gostrc** [comment]
This works, though I don't think it's ideal.

If I were to go with this solution, I would have to special case fetching byte data for all rotate and table_map events.

I think another solution could be to attach a getData method to the EventDataDeserializer class so that we can have a common interface for accessing byte data for all event types.

**Comment by shyiko** [comment]
Oh, I know it's far from being ideal. The workaround above I literally wrote while driving back home :) It's something that you can use *now* and not wait for me to change the internal flow (which is on its way).

**Comment by shyiko** [comment]
Fix available in 0.1.2-SNAPSHOT. Starting from 0417068 EventDataDeserializer can be specified regardless of the event type (= no special treatment for TABLE_MAP/ROTATE).

**Comment by shyiko** [comment]
0.1.2 should become available through Maven Central in the next 24h.

**Comment by gostrc** [comment]
@shyiko oh man, thanks for the quick implementation. I didn't want to sound ungrateful in my original post about your workaround. I just wanted to point out that it would be not ideal. Anyways, it seems like you went the extra step for this issue! cheers! :beer:

**Comment by shyiko** [comment]
> I didn't want to sound... 

Not at all, man. I truly appreciate your feedback. :beers:

**Comment by chenyun** [comment]
@shyiko Thanks a lot, after reading #29 #28 , I understand your design. :beers:
