### ISSUE TITLE
How to get column names of a table?

### ISSUE THREAD

**Issue by ngocdaothanh** [shyiko/mysql-binlog-connector-java#30]
In `TableMapEventData` I can get DB name, table name, column types etc. But there's no info about column names.

How to get column names of a table? Is there a feature in mysql-binlog-connector-java to do that? Or must I use other tools like JDBC? It's very helpful if there's instruction about this in the README.

(Sorry this is a question. I don't know a better place to post it so I post it here.)

**Comment by shyiko** [comment]
Hi. 

Unfortunately binary log is missing that piece of information so you'll have to use something like [this](https://github.com/shyiko/mysql-binlog-connector-java/issues/24#issuecomment-43752483).

P.S. This a perfect place for questions. Don't worry. 
P.P.S. Leaving issue open until I add QA section to the readme.md.

**Comment by ngocdaothanh** [comment]
Thanks! :+1: 
I guess this is the most frequently asked question.

I need the column names because I'm about to write a tool to replicate data from MySQL to MongoDB. I'll publish the tool to GitHub and let you know when it's ready, so that you can add it to the "Used by" section in readme.md.

**Comment by ngocdaothanh** [comment]
> I'll publish the tool to GitHub

Here it is:
https://github.com/ngocdaothanh/mydit

**Comment by shyiko** [comment]
Great. Please let me know when it's ready so that I would add it to the "Used by" section. Thank you.

**Comment by ngocdaothanh** [comment]
Thanks :+1: 

It's ready now.
You can download the first version and use it right away:
https://github.com/ngocdaothanh/mydit/releases

In the next version, I'll improve it a little bit as you advised at #32.

**Comment by shyiko** [comment]
Cool :+1:. Added to the readme.md.

**Comment by aaaweisen** [comment]
this point must add
