### ISSUE TITLE
How EventListener#onEvent is executed?

### ISSUE THREAD

**Issue by ngocdaothanh** [shyiko/mysql-binlog-connector-java#32]
This may be related to #15.

I think readme.md should mention how `EventListener#onEvent` is executed.

Is it executed by the network IO thread of mysql-binlog-connector-java? If I have a blocking logic inside `onEvent`, will it cause mysql-binlog-connector-java to stop reading new binlog events? Should I run my logic in separate thread that I manage on my own?

I want to write a high performance data replicator, so I don't want to block mysql-binlog-connector-java from reading new binlog events while my replicator logic runs.

**Comment by shyiko** [comment]
Hi. 

> This may be related to #15.

That ticket is more about refactoring than anything else.

> Is it executed by the network IO thread of mysql-binlog-connector-java?

Information on whether separate thread is started is in javadocs ([connect](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L281) and [connect(timeout)](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L420)). `onEvent ` is always invoked within the same (original or spawned (depending on which `connect` is being used)) thread. 

> If I have a blocking logic inside onEvent, will it cause mysql-binlog-connector-java to stop reading new binlog events? 

Yes. mysql-binlog-connector-java makes no assumption about how it's going to be used. It's up to the user to implement some kind of queue (hopefully with back pressure mechanism in place) if he deems necessary.

> Should I run my logic in separate thread that I manage on my own?

If you want to squeeze every bit of performance (like in your case) then yes. It sure seems like it.

**Comment by ngocdaothanh** [comment]
Thanks for the great info :+1: 
I'll improve my program based on your advice.

May be you should add it to readme.md because it's important and people rarely read everything in the Javadoc.

Also, it's more convenient if you publish the Javadoc online, for example, using the [Github Pages feature](https://help.github.com/articles/creating-project-pages-manually/).

**Comment by shyiko** [comment]
Good point. Reopening issue as a reminder. Thank you.
