### ISSUE TITLE
how  distribute processing   mysql binlog byte data ?

### ISSUE THREAD

**Issue by noobthinker** [shyiko/mysql-binlog-connector-java#33]
distributed processing mysql binlog byte data but not deserializer it.
not deserializer  bytes. only distributed .
sorrry for my bad english.
thank you.

**Comment by shyiko** [comment]
Hi. Are you interested in getting raw event data? If so - take a look at shyiko/mysql-binlog-connector-java#28. Let me know if that's the case. Thank you.

**Comment by noobthinker** [comment]
i read #28.
thank you very much.
i find if replace the EventDeserializer.nextEvent(ByteArrayInputStream inputStream) to return Event(null,null). the dump log stop.
i think distributed byte[] is a bad idea.
so i change my mind.
i will try two pc with BinaryLogClient.
like this:
pc1:thread1:bc1,pc2:thread2:bc2.
pc1 work one minute and then die.
pc2 active.
pc2 work one minute and then die.
pc1 active.

this way not perfect. 

i think the perfect way is 
pc:master,pc1:worker1,pc2:worker2.
the pc:master distributed byte[] to pc1,pc2.
pc1/pc2 get byte[] data and deserialize it.
pc1/pc2 use mutil thread to do the work.

sorry for my bad english.

Thank you once again.

**Comment by shyiko** [comment]
> i find if replace the EventDeserializer.nextEvent(ByteArrayInputStream inputStream) to return Event(null,null). the dump log stop working.

You shouldn't do that. It's expected not to work. If you want to distribute events in their raw form (byte[]) from one node (pc:master in your case) to others (pc1,pc2,...), you could connect BinaryLogClient on the pc:master (like shown below):

```java
BinaryLogClient client = ...
EventDeserializer eventDeserializer = new EventDeserializer(
    new EventHeaderV4Deserializer(),
    new ByteArrayEventDataDeserializer(),
    new HashMap<EventType, EventDataDeserializer>(), // enforces default (ByteArrayEventDataDeserializer) deserializer
    new HashMap<Long, TableMapEventData>()
);
client.setEventDeserializer(eventDeserializer);
client.connect(...);
```
and then register EventListener like so

```java
// should be called before client.connect(...)
binaryLogClient.registerEventListener(new BinaryLogClient.EventListener() {
    
    @Override
    public void onEvent(Event event) {
        EventHeader header = event.getHeader();
        ByteArrayEventData data = event.getData();
        // send header & data to pc1,pc2,...
    }
});
```
  
Each pc1,pc2,... then can use 

```java
        Map<EventType, EventDataDeserializer> eventDataDeserializers = ...;
        // fill eventDataDeserializers map (https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/EventDeserializer.java#L82)
        ...
        // on event do
        EventDataDeserializer eventDataDeserializer = eventDataDeserializers.get(header. getEventType());
        if (eventDataDeserializer == null) {
            eventDataDeserializer = fallback;
        }
        EventData eventData = eventDataDeserializer.deserialize(eventDataAsByteArray);
```

to complete deserialization on their end.

Does that make sense?

**Comment by noobthinker** [comment]
that's perfect!
Thank you very much for everything.

**Comment by shyiko** [comment]
Great. Closing issue then.
