### ISSUE TITLE
Issue connecting to master

### ISSUE THREAD

**Issue by domainret** [shyiko/mysql-binlog-connector-java#40]
Every time I try to connect to any master (mysql 5.5.6) I get the following error:

java.io.EOFException
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:180)
        at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.readZeroTerminatedString(ByteArrayInputStream.java:81)
        at com.github.shyiko.mysql.binlog.network.protocol.GreetingPacket.<init>(GreetingPacket.java:48)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:297)
        at mem_search.Go.main(Go.java:23)

I've tried multiple database server and I tried remote connect as well as running it on the local host. Can't seem to get it to work. Any tips?

**Comment by domainret** [comment]
This is my code...

try{
			
			BinaryLogClient client = new BinaryLogClient("localhost", 3306, "slave1", "slaver#1");
			client.registerEventListener(new EventListener() {

			    public void onEvent(Event event) {
			       System.out.println(event.toString());
			    }
			});
			
			client.connect();
			
		}catch(Exception ex){
			ex.printStackTrace();
		}

**Comment by shyiko** [comment]
Hi. 

Just tried it on 5.5.6. Works fine. So it must be something with your particular setup. Could you please check that:

1. required permissions are all set (see https://github.com/shyiko/mysql-binlog-connector-java/issues/10#issuecomment-31742597 (ignore Nagle algorithm part))
2. server your are trying to connect to is configured appropriately (see https://github.com/shyiko/mysql-binlog-connector-java/issues/20#issuecomment-42526270 (please note that in case of MySQL 5.5.6 slave "log-slave-updates=TRUE" must be "log-slave-updates" (yes, without "=TRUE")))

Let me know if none of these helps.

**Comment by shyiko** [comment]
Closing issue due to "no response".
