### ISSUE TITLE
How to identify which set of events belong to the same mysql transaction?

### ISSUE THREAD

**Issue by ducaddepar** [shyiko/mysql-binlog-connector-java#48]
(This is a question, but I can't apply the question label for some reason).

How to identify which set of events belong to the same mysql transaction?

In EventType.java, there is a comment about the TABLE_MAP event which said that "Row operation events that belong to the same transaction may be grouped into sequences, in which case each such sequence of events begins with a sequence of TABLE_MAP events: one per table used by events in the sequence.". I understood it as we can use TABLE_MAP events as a marker for the beginning of a transaction. However, there's no marker for the end of a transaction. Certainly when seeing a new TABLE_MAP event, that means that the current transaction has ended. But in case of the last happened transaction, how do I process it correctly without an end marker?

**Comment by wushujames** [comment]
When using InnoDb, typically you will see a QUERY event with text of "BEGIN" to start a transaction, and an XID event type to close the transaction. The TABLE_MAP appears after the "BEGIN"

In the MySQL docs at http://dev.mysql.com/doc/internals/en/event-data-for-specific-event-types.html:
```
An XID event is generated for a commit of a transaction that modifies one or more tables of an XA-capable storage engine.
```

I think if you are using MyISAM tables, you will see QUERY event with text "BEGIN" and then a QUERY event with text "COMMIT"

**Comment by wushujames** [comment]
And btw, it is possible to see multiple TABLE_MAP events within a single transaction. If you had a transaction that updates multiple tables, you will see one TABLE_MAP event for each table that was affected.

**Comment by ducaddepar** [comment]
Thanks! I have a couple of follow up questions
- Is the XID in the XID event useful for some purposes or is it just for marking the end of a transaction?
- Can the XID event indicate if the transaction is rolled back?

**Comment by wushujames** [comment]
The XID appears to be the actual "query id" of the transaction. I'm not sure what I "query id" is, but it's somehow related to the transaction.

I did the following test.

```
mysql> set autocommit = 0;
mysql> begin;
mysql> delete from test.user limit 1;
```
At this point, I did this in a separate window:
```
mysql> show engine innodb status\G
```
(This is on MariaDB). 

Somewhere in the output, I saw:
```
---TRANSACTION 484, not started
MySQL thread id 82, OS thread handle 0x7f2ea1d15700, query id 1755 myhost.mydomain.com 10.100.40.67 root
```

Notice the query_id 1755. After I committed that transcation, I looked in the binlogs and saw this:
```
mysql> show binlog events in 'mariadb-bin.000008' from 269177408;
+--------------------+-----------+-------------+-----------+-------------+--------------------------------+
| Log_name           | Pos       | Event_type  | Server_id | End_log_pos | Info                           |
+--------------------+-----------+-------------+-----------+-------------+--------------------------------+
| mariadb-bin.000008 | 269177408 | Query       |        37 |   269177472 | BEGIN                          |
| mariadb-bin.000008 | 269177472 | Table_map   |        37 |   269177614 | table_id: 36 (test.user)  |
| mariadb-bin.000008 | 269177614 | Delete_rows |        37 |   269177770 | table_id: 36 flags: STMT_END_F |
| mariadb-bin.000008 | 269177770 | Xid         |        37 |   269177797 | COMMIT /* xid=1755 */          |
+--------------------+-----------+-------------+-----------+-------------+--------------------------------+
4 rows in set (0.00 sec)
```
Notice the 1755 appears again.

**Comment by wushujames** [comment]
About rolled back transactions, I have noticed that for InnoDB, transactions that are rolled back do not even appear in the binlogs. However, there is a detail: rolled back transactions do not appear in the binlogs as long as the transaction *only* affects InnoDB tables. For transactions that affect MyISAM tables, you will see a QUERY event with text "ROLLBACK".

I think. See https://dev.mysql.com/doc/refman/5.7/en/binary-log.html for more details. Search for "rollback".

**Comment by ducaddepar** [comment]
These are awesome answers! Thanks!

**Comment by pjebs** [comment]
Why use xid instead of gtid?

**Comment by kaykay2208** [comment]
how can we handle transaction that are parallel? 
is it possible that other transaction event can present inside begin ?
