### ISSUE TITLE
How to get DBName and TableName in WriteRowsEvent/UpdateRowsEvent/DeleteRowsEvent

### ISSUE THREAD

**Issue by syed72** [shyiko/mysql-binlog-connector-java#52]
Hi,

if any event like WRITE_ROWS, UPDATE_ROWS, DELETE_ROWS event occurs, how can i get database name and table name  for which the event occurred?

Please let me know if any way to get those details..

Thanks

**Comment by shyiko** [comment]
Hi. Look for TABLE_MAP event ([TableMapEventData](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/event/TableMapEventData.java)). It contains tableId (+ database/table) which you can use together with *RowsEventData::tableId to obtain what you're asking.

**Comment by 564064202** [comment]
help.how can i write my code?
@Override
			public void onEvent(Event event) {
				System.out.println(event);
				ProcessEvent(event);
			}

I need know event type name database name table name
