### ISSUE TITLE
NPE thrown if connecting to bin log at 'mutation' event

### ISSUE THREAD

**Issue by JohnFirth** [shyiko/mysql-binlog-connector-java#60]
In AbstractRowsEventDataDeserializer.deserializeRow(), 
TableMapEventData tableMapEvent = tableMapEventByTableId.get(tableId) returns null if no table map events have preceded the mutation event (DeleteRowsEvent, UpdateRowsEvent, WriteRowsEvent) in question; this leads to an NPE from byte[] types = tableMapEvent.getColumnTypes();

**Comment by shyiko** [comment]
Thank you, John. 
BinaryLogClient will be updated to take care of that problem transparently once #53 is resolved.
