### ISSUE TITLE
Event Data Corrupted

### ISSUE THREAD

**Issue by syed72** [shyiko/mysql-binlog-connector-java#63]
Hi, i faced some weird problem which i am not able to understand,
In Mysql server DELETE event occurred, in which one row got changed 
but in BinaryLogClient event it showing 3 rows got changed and actual row data got corrupted.
After that event, BinaryLogClient got STOP event and invalid event header, invalid server id, invalid current position, which has been never occurred on Mysql Server.

Below is the delete event received:
Event{header=EventHeaderV4{timestamp=1440507420000, eventType=DELETE_ROWS, serverId=1418033283, headerLength=19, dataLength=76, nextPosition=51680175, flags=0}, data=DeleteRowsEventData{tableId=22343771, includedColumns={0, 1, 2, 3, 4}, rows=[
    [12345, 12346, 234512, 'Arti^@^@^@^@^@', '^H^P�'],
    [42224532206715030, null, -6060154040917097731, '$^A', ''],
    [null, null, 8683811263549413632, null, null]
]}}

" 'Arti^@^@^@^@^@', '^H^P�' " got corrupted
Here binlog name: bin.003313 currentpos:51680080 nextPos: 51680175 serverId:1418033 (all are valid) 

next immediate event:
Event{header=EventHeaderV4{timestamp=340114176000, eventType=STOP, serverId=3368484864, headerLength=19, dataLength=322, nextPosition=4279369729, flags=65535}, data=null}

when this STOP event occured below is the binlog name, current position, nextposition, serverId repectively (all are invalid)
bin.003313 4279369388 4279369729 3368484864

next event:
Event{header=EventHeaderV4{timestamp=26000, eventType=UNKNOWN, serverId=65536, headerLength=19, dataLength=-19, nextPosition=100663296, flags=29443}, data=null}

After this client gets reconnected again and tries to connect from bin.003313 100663296 which got form previous event, and its invalid(position never exists)

Communication failure, BinLog: bin.003313 100663296 clientServerId: 532213298 Exception e: com.github.shyiko.mysql.binlog.network.ServerException: Client requested master to start replication from impossible position; the start event position from 'bin.003313' at 100663296, the last event was read from './bin.003313' at 4, the last byte read was read from './bin.003313' at 4.
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:591)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:376)
        at com.github.shyiko.mysql.binlog.BinaryLogClient$4.run(BinaryLogClient.java:516)
        at java.lang.Thread.run(Thread.java:744)

could you please check this?

**Comment by shyiko** [comment]
Interesting. Any chance I could get my hands on that particular binary log?

**Comment by syed72** [comment]
As BInlog in in production, i can't provide that. How can i help you?

**Comment by shyiko** [comment]
Well, I don't need the whole binary log (DELETE_ROWS & proceeding TABLE_FORMAT would be sufficient, I think) but if that's not possible - can you at least specify table definition?

**Comment by syed72** [comment]
Shyiko, I have shared table definition via mail. Please check...

**Comment by shyiko** [comment]
Unfortunately I'm unable to reproduce. Please try latest 0.2.3-SNAPSHOT.
