### ISSUE TITLE
Tag request for version 0.2.3

### ISSUE THREAD

**Issue by az3** [shyiko/mysql-binlog-connector-java#65]
Hello,

In the Maven Central, the latest version is 0.2.3. Would you please tag that release in GitHub?

http://repo1.maven.org/maven2/com/github/shyiko/mysql-binlog-connector-java/0.2.3/

Thanks.

**Comment by shyiko** [comment]
Tagged. 0.2.3 was released as a hotfix for handling packets over 16mb in size. changelog.md updated. Thank you.
