### ISSUE TITLE
How to get TableName in WriteRowsEvent/UpdateRowsEvent/DeleteRowsEvent

### ISSUE THREAD

**Issue by seemabakshi** [shyiko/mysql-binlog-connector-java#67]
How do I get TableName in WriteRows/UpdateRows/DeleteRows events? I tried using TABLE_MAP event, but the problem is - if the table(A),being updated, has some trigger on it for a different table(B), it gives the wrong table name (B). I would like to add a custom deserializer and use tableMapEventByTableId hashmap to get table name by providing tableId there, but there is no way to set original EventDeserializer.tableMapEventByTableId as tablemap for new deserializer. Can you please suggest how to get tablename in my situation. Thanks.

**Comment by shyiko** [comment]
Hi. Right now, if I understand your question correctly, you can use [EventDeserializer(EventHeaderDeserializer, EventDataDeserializer, Map<EventType, EventDataDeserializer>, Map<Long, TableMapEventData>)](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/event/deserialization/EventDeserializer.java#L75). The last argument is a "shared" tablemap which is automatically updated by EventDeserializer. Alternatively you could register EventListener which would maintain your own TABLE_MAP map used by your custom deserializer.

**Comment by seemabakshi** [comment]
Aah I missed that constructor. So something like this?  
InsertRowsEventDataDeserializer insertDeserializer = new InsertRowsEventDataDeserializer(tableMapEventByTableId);
        UpdateRowsEventDataDeserializer updateDeserializer = new UpdateRowsEventDataDeserializer(tableMapEventByTableId);
        DeleteRowsEventDataDeserializer deleteDeserializer = new DeleteRowsEventDataDeserializer(tableMapEventByTableId);
        IdentityHashMap<EventType, EventDataDeserializer> eventDataDeserializers = new IdentityHashMap<EventType, EventDataDeserializer>();
        eventDataDeserializers.put(EventType.WRITE_ROWS, insertDeserializer);
        eventDataDeserializers.put(EventType.UPDATE_ROWS, updateDeserializer);
        eventDataDeserializers.put(EventType.DELETE_ROWS, deleteDeserializer);
        eventDataDeserializers.put(EventType.ROTATE, new RotateEventDataDeserializer());
        eventDataDeserializers.put(EventType.TABLE_MAP, new TableMapEventDataDeserializer());
        
        EventDeserializer eventDeserializer = new EventDeserializer(new EventHeaderV4Deserializer(), new NullEventDataDeserializer(),
                eventDataDeserializers, tableMapEventByTableId);
        client.setEventDeserializer(eventDeserializer);

**Comment by seemabakshi** [comment]
Thanks, I missed that constructor. So something like this ?

InsertRowsEventDataDeserializer insertDeserializer = new InsertRowsEventDataDeserializer(tableMapEventByTableId);
        UpdateRowsEventDataDeserializer updateDeserializer = new UpdateRowsEventDataDeserializer(tableMapEventByTableId);
        DeleteRowsEventDataDeserializer deleteDeserializer = new DeleteRowsEventDataDeserializer(tableMapEventByTableId);
        IdentityHashMap<EventType, EventDataDeserializer> eventDataDeserializers = new IdentityHashMap<EventType, EventDataDeserializer>();
        eventDataDeserializers.put(EventType.WRITE_ROWS, insertDeserializer);
        eventDataDeserializers.put(EventType.UPDATE_ROWS, updateDeserializer);
        eventDataDeserializers.put(EventType.DELETE_ROWS, deleteDeserializer);
        eventDataDeserializers.put(EventType.ROTATE, new RotateEventDataDeserializer());
        eventDataDeserializers.put(EventType.TABLE_MAP, new TableMapEventDataDeserializer());
        EventDeserializer eventDeserializer = new EventDeserializer(new EventHeaderV4Deserializer(), new NullEventDataDeserializer(),
                eventDataDeserializers, tableMapEventByTableId);
        client.setEventDeserializer(eventDeserializer);

**Comment by shyiko** [comment]
Yes, that's one way to do it.
