### ISSUE TITLE
Jar built from master branch does not work

### ISSUE THREAD

**Issue by xnxky** [shyiko/mysql-binlog-connector-java#73]
Hi, Stanley

Thanks for the great work and we have been using it for some time. Now, we are trying to make some changes on it for our own project. However, if I run "mvn package" on the master branch I cloned from github without making any changes, and then use the jar created, it breaks the our serializer when converting; However, if I use it via maven repo in gradle ("com.github.shyiko:mysql-binlog-connector-java:0.2.4"), it works fine!  Any idea what I did wrong? My maven version is 3.3.3, and java is 1.8.

**Comment by shyiko** [comment]
Hi.

`master` contains changes for upcoming 1.0.0 release and some of them are not backward compatible (as stated in [changelog.md](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/changelog.md)) (subject to change). The easiest way for you to incorporate whatever changes you need is to checkout [0.2.4](https://github.com/shyiko/mysql-binlog-connector-java/tree/0.2.4) tag.

**Comment by xnxky** [comment]
Thanks for the help. Using tag 0.2.4 works. Cheers !
