### ISSUE TITLE
Type "Text" converts into int Array

### ISSUE THREAD

**Issue by MuhammadAmmad** [shyiko/mysql-binlog-connector-java#76]
Hi @shyiko, I m using v 0.2.0. varchar works fine but text is converted into int array 

in mysql: attendance::user::1::17
in java: [97,116,116,101,110,100,97,110,99,101,58,58,117,115,101,114,58,58,49,58,58,49,55]

any suggestion?

**Comment by az3** [comment]
```
String value = new String((byte[]) c, StandardCharsets.UTF_8);

**Comment by MuhammadAmmad** [comment]
Thanks alot @az3

**Comment by shyiko** [comment]
@az3 thank you for taking care of it :+1:
