### ISSUE TITLE
Using mysql-binlog-connector-java withfrom Amazon RDS.

### ISSUE THREAD

**Issue by bbnsumanth** [shyiko/mysql-binlog-connector-java#78]
Can I use  mysql-binlog-connector  to extract logs from Amazon RDS.If its possible,how can we achieve that.Any reference links will be highly helpful.

**Comment by shyiko** [comment]
Hi. Haven't tried it myself but considering that one can use `mysqlbinlog` command line utility (as described [here](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_LogAccess.Concepts.MySQL.html)) there should be no problems. `new BinaryLogClient("MySQL56Instance1.cg034hpkmmjt.region.rds.amazonaws.com", 3306, "username", "password").connect()` should work just fine.
