### ISSUE TITLE
It is wrong value when it read a longtext column

### ISSUE THREAD

**Issue by Muyoo** [shyiko/mysql-binlog-connector-java#79]
There is a column, which type is longtext, in my table. When I write normal values into this column, what I get from the reader is an abnormal string. It looks like a pointer address of a string. 
e.g.: my normal string is "{'arm64':'test', 'is_test':0}", i get this:  [B@704f1591

I don't know how to fix this. 
Any suggestions are welcome! Thx!

**Comment by shyiko** [comment]
Hi. LONGTEXT is returned as byte array (as you can see [here](https://github.com/shyiko/mysql-binlog-connector-java/blob/0.2.4/src/test/java/com/github/shyiko/mysql/binlog/BinaryLogClientIntegrationTest.java#L238)). All you need to do to convert it to the String is to `new String(byteArray, charset)`.

**Comment by BenSkeleton** [comment]
Hi shyiko!
Maybe its a really stupid question, but I really can't figure it out..
The cells are returned as Serializable, not as byte array.

How can I convert the Serializable Object to a byte array to pass it to the String constructor as you wrote?

The only way I could see the proper deserialized Strings was to serialize the Serializable Object to a byte array with a ByteArrayOutputStream. But still there are random characters at the beginning of the String I finally get, that don't belong to the original database entry. Seems like I'm serializing the already serialized object again..

Thanks in advance!

**Comment by az3** [comment]
@BenSkeleton Take a look at this example, maybe it helps: https://github.com/shyiko/mysql-binlog-connector-java/issues/76#issuecomment-157701205
Cheers.

**Comment by shyiko** [comment]
@BenSkeleton and [here](https://github.com/shyiko/mysql-binlog-connector-java/blob/0.5.1/src/test/java/com/github/shyiko/mysql/binlog/BinaryLogClientIntegrationTest.java#L243) (to get the idea of what to expect for different types of columns).

**Comment by BenSkeleton** [comment]
Thanks a lot for the quick responses, I will try it next week, for now I have weekend :-)
