### ISSUE TITLE
Possible bug from open-replicator

### ISSUE THREAD

**Issue by wushujames** [shyiko/mysql-binlog-connector-java#81]
FYI, Zendesk found a bug in their fork of open-replicator. I know that mysql-binlog-connector-java is derived from open-replicator. You might want to see if if affects you. See  https://github.com/zendesk/open-replicator/pull/13

**Comment by shyiko** [comment]
Thanks, @wushujames. I think we have fixed it a while ago (like a year ago - https://github.com/shyiko/mysql-binlog-connector-java/blob/master/changelog.md#011---2014-12-08 :)).

**Comment by wushujames** [comment]
:+1:
