### ISSUE TITLE
question: Does this connector also support create/drop/alter table statements?

### ISSUE THREAD

**Issue by radek1st** [shyiko/mysql-binlog-connector-java#82]
I haven't seen any corresponding EventData...

**Comment by shyiko** [comment]
It does. You should get QUERY event with QueryEventData containing "sql".

**Comment by radek1st** [comment]
Thanks.

On Wed, Jan 13, 2016 at 11:41 PM, Stanley Shyiko <notifications@github.com>
wrote:

> It does. You should get QUERY event with QueryEventData containing "sql".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shyiko/mysql-binlog-connector-java/issues/82#issuecomment-171528185>
> .
>



-- 
Radek

**Comment by 564064202** [comment]
QueryEventData  ? which eventtype?
