### ISSUE TITLE
question: How can I tell if all the events have been read? 

### ISSUE THREAD

**Issue by radek1st** [shyiko/mysql-binlog-connector-java#83]
In my app, whenever it processes all the binlog events, I want it to exit.
Some time later, I'd run it again starting from last recorded position/filename.
Is there a way to achieve that? I don't want to have a process running constantly.
With `mysqlbinlog`, I would remove `--stop-never` flag.

Thanks in advance

**Comment by shyiko** [comment]
https://github.com/shyiko/mysql-binlog-connector-java/commit/24d2588005b43ebd55098331d6d75042f9547d02

**Comment by radek1st** [comment]
Thanks, any idea when this could be released?

**Comment by shyiko** [comment]
@radek1st going to release it as part of backport from master - 0.3.0. It should hit Maven Central withing next 24 hours.
