### ISSUE TITLE
Issue with isBlocking

### ISSUE THREAD

**Issue by radek1st** [shyiko/mysql-binlog-connector-java#84]
Hi again,

I'm setting: 
```
client.setBlocking(false)
client.connect()
```

I start at the end of the binlog, so it disconnects almost straight away, however it hangs for a minute or so and then connects again, and again, and again... Here's the log (running on git master):

```
Got response from PositionSaver: "{\"position\":\"107\",\"file\":\"mysql-bin.000083\"}"
Jan 15, 2016 3:14:35 PM com.github.shyiko.mysql.binlog.BinaryLogClient connect
onConnect
INFO: Connected to 127.0.0.1:9906 at mysql-bin.000083/107 (cid:3061)
ROTATE position = 107; filename = mysql-bin.000083
onDisconnect
Jan 15, 2016 3:15:35 PM com.github.shyiko.mysql.binlog.BinaryLogClient$3 run
INFO: Trying to restore lost connection to 127.0.0.1:9906
Jan 15, 2016 3:15:36 PM com.github.shyiko.mysql.binlog.BinaryLogClient connect
onConnect
INFO: Connected to 127.0.0.1:9906 at mysql-bin.000083/107 (cid:3063)
ROTATE position = 107; filename = mysql-bin.000083
onDisconnect
Jan 15, 2016 3:16:36 PM com.github.shyiko.mysql.binlog.BinaryLogClient$3 run
INFO: Trying to restore lost connection to 127.0.0.1:9906
onConnect
Jan 15, 2016 3:16:36 PM com.github.shyiko.mysql.binlog.BinaryLogClient connect
INFO: Connected to 127.0.0.1:9906 at mysql-bin.000083/107 (cid:3066)
ROTATE position = 107; filename = mysql-bin.000083
onDisconnect
...
```

**Comment by wushujames** [comment]
Sounds like you may have the keep alive thread on? The keep alive thread will auto-reconnect you if you are disconnected. Try client.setKeepAlive(false)

**Comment by radek1st** [comment]
wouldn't setting setKeepAlive to false reduce the ability to reconnect if there is a genuine connection issue?

**Comment by shyiko** [comment]
@radek1st good catch! Thanks.

**Comment by shyiko** [comment]
@wushujames thank you for the help too :+1:

**Comment by radek1st** [comment]
@shyiko @wushujames thanks for quick turnaround :)

**Comment by radek1st** [comment]
I've tried the latest code and `setBlocking(false)` but `completeShutdown` is always false:
```
if(this.isConnected()) {
  if(completeShutdown) {
    this.disconnect();
  } else {
    this.disconnectChannel();
  }
}
```

 and it never hit my breakpoint and set `completeShutdown = true`:
```
if(marker1 == -2 && !this.blocking) {
   completeShutdown = true;
   break;
}
```
Could you please have another look?

**Comment by shyiko** [comment]
Works fine on MySQL 5.5.27. Code that I used to test it was `BinaryLogClient binaryLogClient = new BinaryLogClient("localhost", 33061, "msandbox", "msandbox"); binaryLogClient.setBlocking(false); binaryLogClient.connect();`. Can you share the details of your set up?

**Comment by shyiko** [comment]
@radek1st

**Comment by radek1st** [comment]
5.5.46
```
val client = new BinaryLogClient(sourceDB.getString("host"), sourceDB.getInt("port"),
      sourceDB.getString("user"), sourceDB.getString("password"))
client.setBinlogFilename(4)
//last almost-empty file
client.setBinlogPosition("mysql-bin.000083")
client.registerEventListener(eventListener)
client.setEventDeserializer(getEventDeserializer())
client.setBlocking(false)
client.connect()
```
Would non-default deserializers matter in any way?

**Comment by shyiko** [comment]
Found it. https://github.com/shyiko/mysql-binlog-connector-java/blob/0.3.0/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L624. Marker is byte in master and so everything worked. In 0.3.0 however it's int and obviously 0xFE != (byte) 0xFE. Next time no midless git cherry-pick for backporting :).

**Comment by shyiko** [comment]
@radek1st fixed

**Comment by radek1st** [comment]
:+1: Thanks a lot! Just in time for my holiday :)

**Comment by shyiko** [comment]
@radek1st Cheers :beers:
