### ISSUE TITLE
Odd events

### ISSUE THREAD

**Issue by damiencarol** [shyiko/mysql-binlog-connector-java#86]
I see that in logs:

```
Jan 21, 2016 2:44:54 PM com.github.shyiko.mysql.binlog.BinaryLogClient notifyEventListeners
WARNING: binlog.OutputListener@3feba861 choked on Event{header=EventHeaderV4{timestamp=1453383896000, eventType=INTVAR, serverId=4, headerLength=19, dataLength=13, nextPosition=3100788, flags=0}, data=null}
java.lang.NullPointerException
```

**Comment by shyiko** [comment]
Apparently whichever event listener you have attached to the BinaryLogClient does not how to handle  INTVAR (resulted in java.lang.NullPointerException within **your** listener). In other words, it's not mysql-binlog-connector-java bug.

**Comment by damiencarol** [comment]
ok, sorry @shyiko :/

**Comment by shyiko** [comment]
@damiencarol no worries!

**Comment by SockworkOrange** [comment]
Hey @shyiko , I don't understand what you mean - I attached this EventListener:
com.github.shyiko.mysql.binlog.BinaryLogClient.EventListener
And those warnings persist.
this is my sample code - very straight forward:

`    public static void main(String[] args) throws IOException {

        BinaryLogClient client = new BinaryLogClient(...);

        client.registerEventListener(new EventListener() {
            @Override
            public void onEvent(Event event) {
                EventType eventType = event.getHeader().getEventType();

                //if (EventType.isRowMutation(eventType) || eventType == EventType.GTID) {
                    System.out.println("-----   HEADER     ----");
                    System.out.println(event.getHeader().toString());
                    System.out.println("-----    DATA      ----");
                    System.out.println(event.getData().toString());
                //}
            }
        });

        client.connect();
    }`

What am I doing wrong?
