### ISSUE TITLE
MySQL binlog_format = ROW, not able to get SQL string

### ISSUE THREAD

**Issue by Madusudanan** [shyiko/mysql-binlog-connector-java#87]
For sending the queries to other databases, I need the table name as well as the query.

Getting the table name is not possible when binlog_format = mixed (this is by design), so I need binlog_format = row.

Using this I can get the table name by using the below code.

`TableMapEventData tmEvent = event.getData();
String tableName = tmEvent.getTable();
System.out.println(tableName);`

There is a EXT_WRITE_ROWS event that I am able to read, but I am not able to get the SQL right out of it.

`WriteRowsEventData writeEvent =  event.getData();
queryObj = writeEvent.getSQL();`

The above code is throwing a NullPointerException when I try to use it.I used LifecycleListener to listen in and it throws it at onDeserializationFailure.What am I doing wrong here ? Please feel free to tag this as a question if seems to be that way.

**Comment by shyiko** [comment]
Hi. Please read http://dev.mysql.com/doc/refman/5.7/en/binary-log-formats.html. Information about original query will be lost if binlog_format is set to ROW.
