### ISSUE TITLE
Example with WriteRowsEventData

### ISSUE THREAD

**Issue by alolis** [shyiko/mysql-binlog-connector-java#9]
Hello,

I am playing around with mysql-binlog-connector-java and I am failing to understand how exactly do I loop and get the values from a WriteRowsEventData (or UpdatedRowsEventData).

Let's say we got the Event inside onEvent(Event event)...what's next?
In open-replicator you were doing row.getColumns() and you got the column values. 

It's not very clear what to do after you got the rows and how to deserialize (or does this happen automatically?)

Cheers

**Comment by rahulv8** [comment]
Hello
I am getting rows in serialization forms eg: rows=[[115, [B@27c170f0, [B@5451c3a8, 1457481600000, [B@2626b418]] 
if column type is int or bigint then its giving correct otherwise its giving data in serialization forms please help me  to deserialize rows.

**Comment by shyiko** [comment]
@rahulv8 see https://github.com/shyiko/mysql-binlog-connector-java/issues/79#issuecomment-163691538
