### ISSUE TITLE
data layer to rebuild mysql  from mysql-binlog-connector-java

### ISSUE THREAD

**Issue by wanghaisheng** [shyiko/mysql-binlog-connector-java#91]
i have a mysql server on my remote server with row binlog enabled, in my local server i can set up the same data structure (lets say the source schema wont change ).then i want to build a data layer which can consume these events parsing from mysql-binlog-connector-java  to get the exact same mysql database for others to use.is there any existing implementation of these data layer?

**Comment by shyiko** [comment]
Why not to use MySQL's built-in replication?

**Comment by wanghaisheng** [comment]
1.we dont have mcuh control over original server (built by anyone else)
2. right now i want to get familiar with this lib ,eventually get a mysql-->KAFKA---->ANY target(mysql is only one)

**Comment by shyiko** [comment]
While I would still recommend forcing your way through to get native replication set up, MySQL -> Kafka  can be done by https://github.com/mardambey/mypipe. From Kafka -> MySQL depending on your schema (and how generic you want your solution to be) it might be as simple as [replaying change events](https://github.com/shyiko/rook/blob/master/rook-source-mysql/src/main/java/com/github/shyiko/rook/source/mysql/MySQLReplicationStream.java#L245) or a lot more involving (even though possible).

**Comment by wanghaisheng** [comment]
it seems  [this one](https://github.com/aaaweisen/senge-example/tree/gh-pages/commons-cws-utils) can do my job
