### ISSUE TITLE
GTID：data lost

### ISSUE THREAD

**Issue by fjzhuozl** [shyiko/mysql-binlog-connector-java#95]
1、open GTID
2、when BinaryLogClient.EventListener is more time consuming.
3、mariadb the broken connection.
4、the data will be lost when it is re connected.

**Comment by fjzhuozl** [comment]
Slave reconnect will begin to read from the next GTID.

**Comment by shyiko** [comment]
@fjzhuozl Hi. Could you please explain the problem in more details? If you are running MariaDB and want to use GTID you might want to try https://github.com/wenerme/mysql-binlog-connector-java instead (see https://github.com/shyiko/mysql-binlog-connector-java/pull/50). GTID was tested on official (Oracle) & Percona servers only.

**Comment by fjzhuozl** [comment]
MariaDB
