### ISSUE TITLE
A performance problem，I need some help

### ISSUE THREAD

**Issue by zt3862266** [shyiko/mysql-binlog-connector-java#97]
HI shyiko：
       Our production environment is using this program in order to handle data synchronization and decoupling. We monitor the binlog Events and convert the data into JSON format,then put them into Rabbitmq .The real-time performance is very important for us.
        In our production ,there are too many binlog events In the rush hour .I made the following attempt to improve the performance,but the effect is not obvious .....Sometimes there will be a delay 10 minutes or more.
       1.Only deserialize the tables which I care about 
       2.Put the table schema to memory. clear the cache when receive a QUERY event such as "alter table XXXX"
      Do you have any good suggestion or ideas? 

 In addition, thank you very much for your efforts

**Comment by az3** [comment]
Hello,

I have some suggestions;

1. In some tables, the event ordering may not be important to you. For example: an UPDATE on "users" table is relevant to an INSERT to "purchases" so the events occuring in these 2 tables should be ordered (processed sequentially). But, an entry in "complaint_messages" table may not be that important to you; so you can process them in a seperate thread/queue unordered (even multi-threaded).

2. Cache clearing should also occur on every ROTATE event. That may be a sign of server restart. Also keep in mind that if the master server stops unexpectedly, no STOP event would be in binlog.

3. What are you doing with the deserialized events? Do not process them in the same application (or in the same thread) that reads the binlog.

4. I think you are checking "((EventHeaderV4) event.getHeader()).getTimestamp()" variable regularly to decide the latency. But also check the master server. Maybe the master cannot write binlog events as fast as you think. Create a slave (MySQL server) from that server, and see if the same delay (10+ mins) occur.

**Comment by shyiko** [comment]
@zt3862266 Have you tried to replicate that behavior locally? Usually this sort of thing can be easily solved with just a few rounds of profiling. For example, we found that using Calendar for date construction can slow things down by factor of 10 or more depending on how much timestamps you have in your binlog stream (this is why next 1.0.0 release [switched to `long`s for all dates](https://github.com/shyiko/mysql-binlog-connector-java/commit/02a7f3e6c5f5a4dbf22a1370c5a87be8df7fd663)).

**Comment by zt3862266** [comment]
@az3   Thanks a lot . The third point is very helpful!  The thread that reads the binlog(I call it main thread)  just push the Event into Blocking Queue, then I start some worker threads to consume theses events.
Now it can compelete real time!

**Comment by zt3862266** [comment]
@shyiko This is incredible, I will have a look at your code changes
